### ISSUE TITLE
OwnCloud - losing contacts after successful sync

### ISSUE THREAD

**Issue by pejakm** [bitfireAT/davdroid#578] opened 2015-07-10 17:14 UTC
Both 0.8.1 and 0.8.0 versions affected. I sync to ownCloud server (v8.1, *yesterday upgraded* from v8.0) installed on my computer. OwnCloud correctly displays 469 contacts, DAVdroid synchronizes them all (I monitor number of contacts during synchronization), but as soon as it finishes, number of contacts comes down to 37. I tried several times, contacts are always the same. I even uninstalled Viber and WhatsApp, thinking they could mess with contacts. One thing that I noticed, is that vCard version (DAVdroid settings) is 4.0, I'm not sure what was it before upgrade to 0.8.1. On my 4.4.4 rom the vCard version was always 3.0.

Currently I'm running Lollipop (Euphoria OS). Logcat extracted, I can upload if required.

**Comment by devvv4ever** [comment] 2015-07-10 17:23
seems that this could be a new issue with owncloud 8.1. if you downgrade to your previous version of oc does it work?

**Comment by pejakm** [comment] 2015-07-10 17:43
Reverting to ownCloud 8.0 would be too complicated, as I need to remove everything, install previous version and start over. I'll try to figure out the difference between raw vcard file of contacts which remained in DAVdroid and those which didn't.

**Comment by pejakm** [comment] 2015-07-10 19:06
Okay, It was smoother than I thought. :) I reverted ownCloud back to v8.0, started from clean, also started from a clean profile in DAVdroid. This time in options there is vCard v3.0. Appart from that I had to start synchronization twice (first time only ~350 out 470 contacts was synchronized), everything works. Just left to see whether it will survive moving DAVdroid to /system and reboot.

**Comment by devvv4ever** [comment] 2015-07-10 19:37
alright, thanks for the update! yes, I thought of a problem with owncloud because with testing internally we had problems too and the owncloud releases have been always a bit unstable recently (at least with their caldav/carddav part) :]

hopefully they'll fix it soon!

**Comment by pejakm** [comment] 2015-07-10 19:41
I have made a bug report upstream: https://github.com/owncloud/contacts/issues/979.

**Comment by magenbrot** [comment] 2015-07-10 21:11
I have the same problem with OC 8.1 and DAVdroid 0.8.1 since upgrading owncloud. I have tried various times with various options (and also with different devices).
If I sync my contacts with "CardDAV-Sync free" from the play store every contact gets transferred (just without the groups). So maybe DAVdroid needs some changes too?

**Comment by rfc2822** [comment] 2015-07-13 12:39
Maybe this is related to the cookie support introduced with DAVdroid/0.8.1?

Unfortunately, I couldn't test with OwnCloud/8.1 because after the upgrade from 8.0, the OwnCloud Contact/Calendar apps were removed and I can't install them anymore.

**Comment by aslmx** [comment] 2015-07-13 17:51
I have also seen a lot of Sync Issues in the notification drawer. I had not yet connected this to the OC 8.1 update, but now it looks like this is the reason. I'm to lazy to downgrade and upgrade again. 

I achieved the cleanest sync by deleting both databases (phone + oc) and then imported the multi-vcf exported from OC on the phone into the newly created empty Davdroid account.

Took some time until the contacts were uploaded, but then it was at least almost okay. (some addresses seem to have been messed...).

Will try to reduce my contact editing until either side fixes this...

**Comment by mherzberg** [comment] 2015-07-14 22:49
After some debugging I suspect the bug lies within this line in method `deleteAllExceptRemoteNames` in class LocalCollection:319:
`sqlFileNames.add(DatabaseUtils.sqlEscapeString(res.getName()));`
When I checked my contact database on my device before `deleteAllExceptRemoteNames` gets executed, all my owncloud contacts were present and their source ids contained '@foo.bar.de.vcf'. However the `sqlEscapeString` method escapes the @ to %40, so (almost) no contacts matches the sql query anymore and get deleted.  I replaced the line with `			sqlFileNames.add(DatabaseUtils.sqlEscapeString(res.getName()).replace("%40", "@"));`, and my contacts seemed to stay on my device.

**Comment by mhzawadi** [comment] 2015-07-15 18:41
Hi, I get the same issue with both 0.8.0 and 0.8.1 to ownCloud 8.1.

I did notice that the old ownCloud contacts didnt have the vcard 4.0 option ticked.

nginx/1.8.0
PHP 5.4.41-0+deb7u1 (fpm-fcgi) with XCache v2.0.0
ownCloud 8.1.0 with 'memcache.local' => '\OC\Memcache\XCache'
DavDroid/0.8.1 (0.8.0 also) on HTC M8 android 5.0.1

**Comment by pejakm** [comment] 2015-07-15 18:53
> However the sqlEscapeString method escapes the @ to %40, so (almost) no contacts matches the sql query anymore and get deleted. I replaced the line with sqlFileNames.add(DatabaseUtils.sqlEscapeString(res.getName()).replace("%40", "@"));, and my contacts seemed to stay on my device.

Then this is DAVdroid bug, after all.

**Comment by mokkin** [comment] 2015-07-15 22:03
In my case the the sync of several addressbooks from Owncloud 8.1 with DavDroid 0.8.1 works fine, but the calendar sync doesn't work. The account setup works and it says "synced" but nothing is displayed.

**Comment by julienval** [comment] 2015-07-16 11:32
> However the sqlEscapeString method escapes the @ to %40, so (almost) no contacts matches the sql query anymore and get deleted. I replaced the line with sqlFileNames.add(DatabaseUtils.sqlEscapeString(res.getName()).replace("%40", "@"));, and my contacts seemed to stay on my device.

I would be happy to test your change if you can supply a precompiled apk
I can reproduce the issue on both of my phones

**Comment by flocke** [comment] 2015-07-17 08:18
I would be available for testing as well. Just upload a apk somewhere and give me the link.

**Comment by mherzberg** [comment] 2015-07-17 09:19
Here is the link to my test build: ![davdroid-debug.apk](https://gist.github.com/mherzberg/4fc9984db0577576449d/raw/f3073fcf35748e77c06515b201c278f3a9bd9c36/davdroid-debug.apk)
Please note that this is just a test build from me related to this issue and should not be used for daily usage. I do not take any responsibility for any harm caused by using this apk.

This is the git diff from the code I used:
```
diff --git a/app/src/main/java/at/bitfire/davdroid/resource/LocalAddressBook.java b/app/src/main/java/at/bitfire/davdroid/resource/LocalAddressBook.java
index 65e2891..3479ac9 100644
--- a/app/src/main/java/at/bitfire/davdroid/resource/LocalAddressBook.java
+++ b/app/src/main/java/at/bitfire/davdroid/resource/LocalAddressBook.java
@@ -139,7 +139,7 @@ public class LocalAddressBook extends LocalCollection<Contact> {
                if (remoteResources.length != 0) {
                        List<String> sqlFileNames = new LinkedList<>();
                        for (Resource res : remoteResources)
-                               sqlFileNames.add(DatabaseUtils.sqlEscapeString(res.getName()));
+                               sqlFileNames.add(DatabaseUtils.sqlEscapeString(res.getName()).replace("%40", "@"));
                        where = entryColumnRemoteName() + " NOT IN (" + StringUtils.join(sqlFileNames, ",") + ")";
                } else
                        where = entryColumnRemoteName() + " IS NOT NULL";
```

**Comment by rfc2822** [comment] 2015-07-17 21:44
I can't reproduce that.

```
Log.i(TAG, "SQLite escaped: " + DatabaseUtils.sqlEscapeString("a@b.com"));
```

gives `a@b.com` here.

**Comment by rfc2822** [comment] 2015-07-17 23:51
When trying to reproduce this bug, I ran into https://github.com/owncloud/contacts/issues/808. Is sharing enabled in your installation? If not, can you try to enable it?

Can you please

1. delete or rename your OwnCloud log (`data/owncloud.log`)
2. do a DAVdroid sync
3. access Contacts module in the Web Interface
4. post the contents of your `owncloud.log`

**Comment by protist** [comment] 2015-07-18 01:53
I can confirm that mherzberg's apk fixes this for me. Thank you!

Previously, I was getting error messages in the notification menu every hour or so. Unfortunately, I forget what they said precisely.

I attempted uninstalling DAVdroid, then installing version 0.7.7. My phone would only import three contacts (out of 150). Oddly enough, I think these were the only contacts that I had added via the phone/DAVdroid. The others had been added/imported via OwnCloud's web interface a while ago.

I also attempted installing DAVdroid 0.8.0 and 0.8.1. Neither fixed this issue. Only when installing mherzberg fix did it work. Thanks again!

**Comment by protist** [comment] 2015-07-18 02:20
Ahhh… after a while I've noticed mherzberg's apk is buggy too. Every time DAVdroid syncs, it creates an additional copy of each contact, *except* the three contacts that were the only ones synced in the official versions of DAVdroid (as per my previous post). Hence, after three syncs, I have one copy of these original three in my Android address book as expected, but three copies of every other contact!

**Comment by julienval** [comment] 2015-07-18 05:47
@rfc822 : sharing is enabled on my OC setup. I have followed your steps but my log file is empty after calling the contact page.

I have installed mherzberg's apk on both of my phones and it seems to fix the issue. I have tried several syncs and I haven't encountered the issue reported by protist.

**Comment by rfc2822** [comment] 2015-07-18 06:34
Can someone provide a test account with contacts that show the behaviour with DAVdroid 0.8.1, so that I can reproduce the issue?

I guess the file name is stored URL-encoded, unrelated to SQL escaping, but I can't test as it works here.

**Comment by julienval** [comment] 2015-07-18 07:00
Done, I have just sent you the details through your blog contact page.

**Comment by rfc2822** [comment] 2015-07-18 07:08
Didn't get anything, maybe hit by the spam filter or so. Can you please send it to play@bitfire.at again

**Comment by mherzberg** [comment] 2015-07-18 11:00
> Can you back this up? I don't think @ should be escaped in SQL strings, and sqlEscapeString doesn't behave like that here.

You're right, I was too quick to assume that. The encoding issue seems to come from the different http request types (propfind vs report). Anyway, please try if you can reproduce the issue as follows:

- Create a new address book in the owncloud web interface and import the following as an contacts.vcf file (the issue is only present with two or more contacts):
```
BEGIN:VCARD
VERSION:3.0
PRODID:-//ownCloud//NONSGML Contacts 0.3.0.18//EN
FN:FOO
N:;FOO;;;
UID:20140623T46782.acdf@foo.bar.vcf
REV:2015-07-15T01:18:20+00:00
END:VCARD

BEGIN:VCARD
VERSION:3.0
PRODID:-//ownCloud//NONSGML Contacts 0.3.0.18//EN
FN:BAR
N:;BAR;;;
UID:20140623T00123.086fed@foo.bar.vcf
REV:2015-07-15T01:18:21+00:00
END:VCARD
```
- Import this address book into DavDroid. This creates the following log lines for me. Please note the different encodings of '@' in the ```Processing multi-status element``` lines.
```
I/davdroid.DavSyncAdapter﹕ Performing sync for authority com.android.contacts
D/davdroid.DavSyncAdapter﹕ Creating new DavHttpClient
V/davdroid.URIUtils﹕ Normalized URI https://foo.bar.de/remote.php/carddav/addressbooks/test/contacts/ -> https://foo.bar.de/remote.php/carddav/addressbooks/test/contacts/ assuming that it was an URI or path name
D/davdroid.WebDavResource﹕ Using preemptive authentication (not compatible with Digest auth)
I/davdroid.SyncManager﹕ Remotely removing 0 deleted resource(s) (if not changed)
I/davdroid.SyncManager﹕ Uploading 0 new resource(s) (if not existing)
I/davdroid.SyncManager﹕ Uploading 0 modified resource(s) (if not changed)
V/davdroid.URIUtils﹕ Normalized URI /remote.php/carddav/addressbooks/test/contacts/ -> /remote.php/carddav/addressbooks/test/contacts/ assuming that it was an URI or path name
D/davdroid.WebDavResource﹕ Processing multi-status element: https://foo.bar.de/remote.php/carddav/addressbooks/test/contacts/
D/davdroid.SyncManager﹕ Last local CTag = null; current remote CTag = 1437215802
I/davdroid.SyncManager﹕ Fetching remote resource list
V/davdroid.URIUtils﹕ Normalized URI /remote.php/carddav/addressbooks/test/contacts/ -> /remote.php/carddav/addressbooks/test/contacts/ assuming that it was an URI or path name
D/davdroid.WebDavResource﹕ Processing multi-status element: https://foo.bar.de/remote.php/carddav/addressbooks/test/contacts/
V/davdroid.URIUtils﹕ Normalized URI /remote.php/carddav/addressbooks/test/contacts/20140623T46782.acdf%2540foo.bar.vcf.vcf -> /remote.php/carddav/addressbooks/test/contacts/20140623T46782.acdf%2540foo.bar.vcf.vcf assuming that it was an URI or path name
D/davdroid.WebDavResource﹕ Processing multi-status element: https://foo.bar.de/remote.php/carddav/addressbooks/test/contacts/20140623T46782.acdf%2540foo.bar.vcf.vcf
V/davdroid.URIUtils﹕ Normalized URI /remote.php/carddav/addressbooks/test/contacts/20140623T00123.086fed%2540foo.bar.vcf.vcf -> /remote.php/carddav/addressbooks/test/contacts/20140623T00123.086fed%2540foo.bar.vcf.vcf assuming that it was an URI or path name
D/davdroid.WebDavResource﹕ Processing multi-status element: https://foo.bar.de/remote.php/carddav/addressbooks/test/contacts/20140623T00123.086fed%2540foo.bar.vcf.vcf
I/davdroid.SyncManager﹕ Fetching 2 new remote resource(s)
I/davdroid.resource﹕ Multi-getting 2 remote resource(s)
V/davdroid.URIUtils﹕ Normalized URI /remote.php/carddav/addressbooks/test/contacts/20140623T00123.086fed@foo.bar.vcf.vcf -> /remote.php/carddav/addressbooks/test/contacts/20140623T00123.086fed@foo.bar.vcf.vcf assuming that it was an URI or path name
D/davdroid.WebDavResource﹕ Processing multi-status element: https://foo.bar.de/remote.php/carddav/addressbooks/test/contacts/20140623T00123.086fed@foo.bar.vcf.vcf
V/davdroid.URIUtils﹕ Normalized URI /remote.php/carddav/addressbooks/test/contacts/20140623T46782.acdf@foo.bar.vcf.vcf -> /remote.php/carddav/addressbooks/test/contacts/20140623T46782.acdf@foo.bar.vcf.vcf assuming that it was an URI or path name
D/davdroid.WebDavResource﹕ Processing multi-status element: https://foo.bar.de/remote.php/carddav/addressbooks/test/contacts/20140623T46782.acdf@foo.bar.vcf.vcf
D/davdroid.SyncManager﹕ Adding 20140623T00123.086fed@foo.bar.vcf.vcf
D/davdroid.Collection﹕ Committing 2 operations ...
D/davdroid.Collection﹕ ... 0 row(s) affected
D/davdroid.SyncManager﹕ Adding 20140623T46782.acdf@foo.bar.vcf.vcf
D/davdroid.Collection﹕ Committing 2 operations ...
D/davdroid.Collection﹕ ... 0 row(s) affected
I/davdroid.SyncManager﹕ Fetching 0 updated remote resource(s)
I/davdroid.SyncManager﹕ Removing non-dirty resources that are not present remotely anymore
```

Both contacts get created and immediately deleted afterwards on my phone. I hope this helps in nailing down the issue.

**Comment by rfc2822** [comment] 2015-07-18 11:36
> Both contacts get created and immediately deleted afterwards on my phone. I hope this helps in nailing down the issue.

Yes, this seems to reproducable here. I'll have a look.

**Comment by rfc2822** [comment] 2015-07-18 12:12
Let's have a look at what is happening:

First, DAVdroid requests a list of all members from the server:

```
http-outgoing-0 >> "PROPFIND /owncloud/remote.php/carddav/addressbooks/test/kontakte/ HTTP/1.1[\r][\n]"
http-outgoing-0 << "<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:card="urn:ietf:params:xml:ns:carddav"><d:response><d:href>/owncloud/remote.php/carddav/addressbooks/test/kontakte/</d:href><d:propstat><d:prop><x3:getctag xmlns:x3="http://calendarserver.org/ns/">1437219316</x3:getctag></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat><d:propstat><d:prop><d:getetag/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response><d:response><d:href>/owncloud/remote.php/carddav/addressbooks/test/kontakte/20140623T46782.acdf%2540foo.bar.vcf.vcf</d:href><d:propstat><d:prop><d:getetag>"28c05d52626ce5084a1f991b438ac41d"</d:getetag></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat><d:propstat><d:prop><x3:getctag xmlns:x3="http://calendarserver.org/ns/"/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response><d:response><d:href>/owncloud/remote.php/carddav/addressbooks/test/kontakte/20140623T00123.086fed%2540foo.bar.vcf.vcf</d:href><d:propstat><d:prop><d:getetag>"f144eaeea375650281aeeff2929788bd"</d:getetag></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat><d:propstat><d:prop><x3:getctag xmlns:x3="http://calendarserver.org/ns/"/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response></d:multistatus>[\n]"
```

The pretty-printed response is:

```
<d:response>
    <d:href>/owncloud/remote.php/carddav/addressbooks/test/kontakte/20140623T46782.acdf%2540foo.bar.vcf.vcf</d:href>
    <d:propstat>
        <d:prop>
            <d:getetag>"28c05d52626ce5084a1f991b438ac41d"</d:getetag>
        </d:prop>
        <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
    <d:propstat>
        <d:prop>
            <x3:getctag xmlns:x3="http://calendarserver.org/ns/"/>
        </d:prop>
        <d:status>HTTP/1.1 404 Not Found</d:status>
    </d:propstat>
</d:response>
<d:response>
    <d:href>/owncloud/remote.php/carddav/addressbooks/test/kontakte/20140623T00123.086fed%2540foo.bar.vcf.vcf</d:href>
    <d:propstat>
        <d:prop>
            <d:getetag>"f144eaeea375650281aeeff2929788bd"</d:getetag>
        </d:prop>
        <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
    <d:propstat>
        <d:prop>
            <x3:getctag xmlns:x3="http://calendarserver.org/ns/"/>
        </d:prop>
        <d:status>HTTP/1.1 404 Not Found</d:status>
    </d:propstat>
</d:response>
</d:multistatus>
```

So, there are two (new) members:
* `/owncloud/remote.php/carddav/addressbooks/test/kontakte/20140623T46782.acdf%2540foo.bar.vcf.vcf` (URL-encoded), i.e. member name `20140623T46782.acdf%40foo.bar.vcf.vcf` (unencoded)
* `/owncloud/remote.php/carddav/addressbooks/test/kontakte/20140623T00123.086fed%2540foo.bar.vcf.vcf` (URL-encoded), i.e. member name `20140623T00123.086fed%40foo.bar.vcf.vcf` (unencoded)

DAVdroid requests those two resources via REPORT addressbook-multiget:

```
http-outgoing-0 >> "REPORT /owncloud/remote.php/carddav/addressbooks/test/kontakte/ HTTP/1.1[\r][\n]"
…
http-outgoing-0 >> "<CD:addressbook-multiget xmlns:CD="urn:ietf:params:xml:ns:carddav" xmlns="DAV:">[\n]"
http-outgoing-0 >> "   <prop>[\n]"
http-outgoing-0 >> "      <CD:address-data content-type="text/vcard" version="4.0"/>[\n]"
http-outgoing-0 >> "      <getetag/>[\n]"
http-outgoing-0 >> "   </prop>[\n]"
http-outgoing-0 >> "   <href>/owncloud/remote.php/carddav/addressbooks/test/kontakte/20140623T00123.086fed%2540foo.bar.vcf.vcf</href>[\n]"
http-outgoing-0 >> "   <href>/owncloud/remote.php/carddav/addressbooks/test/kontakte/20140623T46782.acdf%2540foo.bar.vcf.vcf</href>[\n]"
http-outgoing-0 >> "</CD:addressbook-multiget>"
```

OwnCloud returns:

```
http-outgoing-0 << "HTTP/1.1 207 Multi-Status[\r][\n]"
…
http-outgoing-0 << "<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:card="urn:ietf:params:xml:ns:carddav"><d:response><d:href>/owncloud/remote.php/carddav/addressbooks/test/kontakte/20140623T00123.086fed@foo.bar.vcf.vcf</d:href><d:propstat><d:prop><card:address-data>BEGIN:VCARD&#13;[\n]"
http-outgoing-0 << "VERSION:4.0&#13;[\n]"
http-outgoing-0 << "PRODID:-//Sabre//Sabre VObject 3.4.2//EN&#13;[\n]"
http-outgoing-0 << "FN:BAR&#13;[\n]"
http-outgoing-0 << "N:;BAR;;;&#13;[\n]"
http-outgoing-0 << "UID:20140623T00123.086fed@foo.bar.vcf&#13;[\n]"
http-outgoing-0 << "REV:2015-07-18T11:35:15+00:00&#13;[\n]"
http-outgoing-0 << "END:VCARD&#13;[\n]"
http-outgoing-0 << "</card:address-data><d:getetag>"f144eaeea375650281aeeff2929788bd"</d:getetag></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response><d:response><d:href>/owncloud/remote.php/carddav/addressbooks/test/kontakte/20140623T4678"
http-outgoing-0 << "2.acdf@foo.bar.vcf.vcf</d:href><d:propstat><d:prop><card:address-data>BEGIN:VCARD&#13;[\n]"
http-outgoing-0 << "VERSION:4.0&#13;[\n]"
http-outgoing-0 << "PRODID:-//Sabre//Sabre VObject 3.4.2//EN&#13;[\n]"
http-outgoing-0 << "FN:FOO&#13;[\n]"
http-outgoing-0 << "N:;FOO;;;&#13;[\n]"
http-outgoing-0 << "UID:20140623T46782.acdf@foo.bar.vcf&#13;[\n]"
http-outgoing-0 << "REV:2015-07-18T11:35:15+00:00&#13;[\n]"
http-outgoing-0 << "END:VCARD&#13;[\n]"
http-outgoing-0 << "</card:address-data><d:getetag>"28c05d52626ce5084a1f991b438ac41d"</d:getetag></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response></d:multistatus>[\n]"
```

So, if you have a look, you'll see that DAVdroid requested the resources
* `/owncloud/remote.php/carddav/addressbooks/test/kontakte/20140623T00123.086fed%2540foo.bar.vcf.vcf` (URL-encoded), i.e. the member named `20140623T00123.086fed%40foo.bar.vcf.vcf` (unencoded [%25 decodes to "%"]) and
* `/owncloud/remote.php/carddav/addressbooks/test/kontakte/20140623T46782.acdf%2540foo.bar.vcf.vcf` (URL-encoded) i.e. the member named `20140623T46782.acdf%40foo.bar.vcf.vcf` (unencoded)

However, OwnCloud returned 
* `/owncloud/remote.php/carddav/addressbooks/test/kontakte/20140623T00123.086fed@foo.bar.vcf.vcf` and
* `/owncloud/remote.php/carddav/addressbooks/test/kontakte/20140623T46782.acdf@foo.bar.vcf.vcf`

This is clearly not what was requested and OwnCloud does one additional (and erroneous) level of encoding (as DAVdroid did earlier).

So, the sync process happens like this:

1. In reseponse to PROPFIND, OwnCloud tells DAVdroid that there are two members:
   * `20140623T00123.086fed%40foo.bar.vcf.vcf` (unencoded) and
   * `20140623T46782.acdf%40foo.bar.vcf.vcf` (unencoded)
2. DAVdroid requests these two (new) members from OwnCloud and adds all resources from the response. The response however
   does not contain the requested members, but `20140623T00123.086fed@foo.bar.vcf.vcf` and `/owncloud/remote.php/carddav/addressbooks/test/kontakte/20140623T46782.acdf@foo.bar.vcf.vcf`.
   These resources are added nevertheless (because DAVdroid expects them to be the requested ones).
3. DAVdroid deletes everything except `20140623T00123.086fed%40foo.bar.vcf.vcf` (unencoded) and `20140623T46782.acdf%40foo.bar.vcf.vcf`,
   so the recently fetched resources are deleted immediately (because their names are `20140623T00123.086fed@foo.bar.vcf.vcf`
   and `/owncloud/remote.php/carddav/addressbooks/test/kontakte/20140623T46782.acdf@foo.bar.vcf.vcf`).

**Why does it work when there's only one new record?** In this case, DAVdroid uses a `GET` request instead of `REPORT addressbook-multiget`. The response is directly the VCard and the member name is used from the requested URI, so there's no possibility for OwnCloud to return an erroneous file name.

Do you agree?

**Comment by mherzberg** [comment] 2015-07-18 14:20
Yes, I agree with you that the root cause seems to be inconsistent escaping of URIs by owncloud (URI escaped twice (```%2540```) in ```href```-tags in PROPFIND responses vs no escaping in ```href```-tags in REPORT responses). I don't know how it's handled elsewhere in owncloud, but I would expect no escaping at all in those ```href```-tags. So this seems to be a bug in owncloud/the contact app after all. A workaround for this would be to unescape the ``href``-tag twice in received PROPFIND responses, I guess? What do you think?

**Comment by untitaker** [comment] 2015-07-18 14:20
@rfc2822 I think you're hitting https://github.com/owncloud/contacts/issues/581. It's going to be tricky/impossible to fix both #482 and simultaneously work around this. Even if ownCloud fixes this soon (it won't), there will be other servers that do this.

What I'm currently doing is to first decode the filename and then encode it again except for the characters `/@%:`. This fixes only the most common instances of this problem where the encoded `@` is causing trouble.

For the other rare cases I provide a `repair` command that fixes filenames to only use alphanumeric characters. I don't think that's within the scope of a sync app, but I've found it necessary as people came to me with the most perverse encoding problems. Now I can tell them to run the `repair` command and everything just works out.

**Comment by rfc2822** [comment] 2015-07-18 14:36
@untitaker This could be the cause. The SabreDAV issue is closed, so couldn't this be applied to OwnCloud too?

**Comment by untitaker** [comment] 2015-07-18 14:38
The sabredav issue is closed because it's a bug in ownCloud (somewhere in that conversation is a link to the exact line). I don't know if e.g. Baikal has this issue.

**Comment by rfc2822** [comment] 2015-07-18 14:41
Ok, so it seems the problem is caused by OwnCloud. Funny that it worked with older DAVdroid versions just because DAVdroid hat the opposite bug (it was quite a privacy killer to be honest, calling remote URLs just because of a file name).

**Comment by untitaker** [comment] 2015-07-18 14:48
BTW what's the behavior if a PROPFIND request returns a 404 for some hrefs? Are these hrefs skipped? You might be able to turn such silent failures into hard crashes by raising an error for those (an improvement IMO, but I understand if that's not the UI you want)

**Comment by rfc2822** [comment] 2015-07-18 14:54
> BTW what's the behavior if a PROPFIND request returns a 404 for some hrefs? Are these hrefs skipped?

For every response in a 207-multi-response, [the same `checkResponse` is called](https://github.com/bitfireAT/davdroid/blob/ad733ebff138a598b6fd2487f9bbc1724f475656/app/src/main/java/at/bitfire/davdroid/webdav/WebDavResource.java#L483) as it would be called for a single GET.

[checkResponse](https://github.com/bitfireAT/davdroid/blob/ad733ebff138a598b6fd2487f9bbc1724f475656/app/src/main/java/at/bitfire/davdroid/webdav/WebDavResource.java#L417) will accept 10x and 20x silently and throw an exception for other status codes.

But it's off-topic ;)

**Comment by untitaker** [comment] 2015-07-18 15:33
It's somewhat related because I wonder how DavDroid would delete contacts if a PROPFIND request doesn't return the requested hrefs.

On 18 July 2015 16:54:13 CEST, rfc2822 <notifications@github.com> wrote:
>> BTW what's the behavior if a PROPFIND request returns a 404 for some
>hrefs? Are these hrefs skipped?
>
>For every response in a 207-multi-response, [the same `checkResponse`
>is
>called](https://github.com/bitfireAT/davdroid/blob/ad733ebff138a598b6fd2487f9bbc1724f475656/app/src/main/java/at/bitfire/davdroid/webdav/WebDavResource.java#L483)
>as it would be called for a single GET.
>
>[checkResponse](https://github.com/bitfireAT/davdroid/blob/ad733ebff138a598b6fd2487f9bbc1724f475656/app/src/main/java/at/bitfire/davdroid/webdav/WebDavResource.java#L417)
>will accept 10x and 20x silently and throw an exception for other
>status codes.
>
>But it's off-topic ;)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/bitfireAT/davdroid/issues/578#issuecomment-122550656

-- 
Sent from my phone. Please excuse my brevity.

**Comment by rfc2822** [comment] 2015-07-18 15:38
> It's somewhat related because I wonder how DavDroid would delete contacts if a PROPFIND request doesn't return the requested hrefs.

I don't understand the question. DAVdroid deletes all local contacts which are not returned by PROPFIND, based on the file name, at the end of the sync process.

**Comment by untitaker** [comment] 2015-07-18 15:45
Sorry, I think I confused PROPFIND with an addressbook-multiget REPORT.

On 18 July 2015 17:38:27 CEST, rfc2822 <notifications@github.com> wrote:
>> It's somewhat related because I wonder how DavDroid would delete
>contacts if a PROPFIND request doesn't return the requested hrefs.
>
>I don't understand the question. DAVdroid deletes all local contacts
>which are not returned by PROPFIND, based on the file name, at the end
>of the sync process.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/bitfireAT/davdroid/issues/578#issuecomment-122556983

-- 
Sent from my phone. Please excuse my brevity.

**Comment by Eddy1979** [comment] 2015-07-24 09:46
Same problem when I restore my second smartphone.
Both phones have the same android (4.4.2) and davdroid (8.1) versions.
On my first smartphone the sync is working perfectly. On my second phone all contacts are deleted after a while.
On the 2nd phone, when I go in the settings: contacts are sent in vcard 4.0 format (always tick on)
On the first phone, when I go in the settings: contacts are sent in vcard 3.0 format (always tick off)
I don't understand why???

**Comment by rfc2822** [comment] 2015-07-24 10:29
@Eddy1979 Without detailed logs, there's no way to analyze your problem. It's very likely that you're hit by the OwnCloud bug discussed here. The two phones probably behave differently because the accounts on the phones were created with different DAVdroid and/or OwnCloud versions. Uninstall and then install DAVdroid again on both phones and they will most likely behave identically. The VCard version of the server is detected when the account is created and shown in the Settings UI (it can't be changed).

**Comment by Eddy1979** [comment] 2015-07-24 11:16
@rfc2822 thank you for your fast reply.
If I understand the only one solution is to wait for an OC update. :-(

**Comment by mherzberg** [comment] 2015-07-24 11:23
Well, a possible workaround for the bug discussed here is, as mentioned somewhere above, to export all your contacts, make sure the ids do not contain special characters such as '@', and then re-import them into your owncloud.

**Comment by untitaker** [comment] 2015-07-24 22:23
I think I understand now what was irking me about DavDroid's behavior:

>delete every local non-dirty contacts that are not on the server anymore

The items with `@` are being treated inconsistently by DavDroid. First it assumes they're on the server and therefore adds them to the addressbook, later it thinks they are not on the server and deletes them.

**Comment by Raydiation** [comment] 2015-07-25 20:39
To clear up things: The contacts app is not maintained, the maintainer left the project because of disagreements with how things were decided and communicated back then. I feel that things got better. 

Long story short: this won't be fixed and the code is quite messy. We need someone who wants to fix things and is able to write PHP and JavaScript. If someone is interested, I'd offer help to get into ownCloud's PHP API and would help to review code.

**Comment by untitaker** [comment] 2015-07-26 06:24
I'm willing to provide a patch for this particular bug but definetly can't take over maintainership.

On 25 July 2015 22:39:55 CEST, Bernhard Posselt <notifications@github.com> wrote:
>To clear up things: The contacts app is not maintained, the maintainer
>left the project because of disagreements with how things were decided
>and communicated back then. I feel that things got better. 
>
>Long story short: this won't be fixed and the code is quite messy. We
>need someone who wants to fix things and is able to write PHP and
>JavaScript. If someone is interested, I'd offer help to get into
>ownCloud's PHP API and would help to review code.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/bitfireAT/davdroid/issues/578#issuecomment-124889149

-- 
Sent from my phone. Please excuse my brevity.

**Comment by mfaure** [comment] 2015-07-31 13:57
Here is my workaround using @untitaker's owncloud/contacts#1003 pull request. To have an OwnCloud 8.1 synchronising correctly and *right now*, I directly modified the `apps/contacts/lib/carddav/backend.php` file, on line 192 I replaced 

```php
'uri' => urlencode($contact['uri']),
```
by

```php
'uri' => $contact['uri'],
```

This may be kind of bully, but it worked for me.

**Comment by Raydiation** [comment] 2015-07-31 14:15
I've added the fix in owncloud contacts

**Comment by rfc2822** [comment] 2015-08-02 07:20
@Raydiation Thanks, so I'll close this issue here now.

**Closed by rfc2822** 2015-08-02 07:20 UTC
Labels: 3rd-party issue

**Comment by NuclearFuzion** [comment] 2015-08-13 13:21
Workaround?

About the bug in UIDs between DAVDroid/OwnCloud, to get rid of the problem on contacts dispappearing in Android, I:
1/ exported the Contacts List file as a .vcf (from Owncloud itseld, from Evolution or from Android, doesn't matter).
2/ Edited this list with the GNU notepad (any other should also work), removing all "@"in the UIDs. (Find/replaceAll)
3/ Remove all contacts from Owncloud/Contacts web interface, imported back the cleaned .vcf file.

I didn't really understand from where these "@" in the UIDs came from (I highly suspect contacts created in previous OC versions), tested a new contact creation from Evolution, Android and OwnCloud/Contacts4.0.0. and all the UIDs are clean, so the problem should disappear in the future, thanks to the fix too.

This might be useful to some people who still have "dirty" UIDs in their contacts files. I'm now on OC8.1.1, DAVDroid 0.8.3 and everything is fine.

**Comment by aslmx** [comment] 2015-08-16 11:12
Exported the contacts, deleted the "@1234..." behind the UIDs and reimported them. Worked like a charm. No more sync errors since then between owncloud and davdroid. Thanks for that great hint!

**Comment by Tronde** [comment] 2015-08-28 07:45
@Raydiation is your fix mentioned in comment [126705900](https://github.com/bitfireAT/davdroid/issues/578#issuecomment-126705900) included in the Release 0.4.0.0 of the Contacts-App? I have difficulties to figure out wether the fix is already included in the current ownCloud release 8.1.1 or not.

**Comment by Raydiation** [comment] 2015-08-28 08:30
The contacts app is not included in 8.1. The fix was made a month ago, contacts 4.0.0 was released 2 months ago, so you need to use master until a new release is uploaded to the app store

**Comment by Tronde** [comment] 2015-08-28 08:37
All right. Thanks for your reply.

**Comment by giuliano52** [comment] 2015-08-29 04:26
The workaround worked for me too (owncloud 8.1 and davroid 0.8.4).
Exported the contacts from owncloud, removed with a text editor all the @ part in the UUID and then reimported. 
Thank you

**Comment by childnode** [comment] 2015-08-31 16:14
I can't see (as discussed in 555) that the UID @ is causing this: 
I have both, working and non-working items with an @ in the uuid.
see my details on https://www.evernote.com/shard/s448/sh/8144b893-7694-4b3f-aaac-cd32e33f647c/184711982f666a9c
to NOT urlencode the uid on owncloud is incorrect to me, since an @ will then be included in any generated .vcf references in PROPGET.

@Raydiation perhaps you might point out the change in oc contacts app?

**Comment by Raydiation** [comment] 2015-08-31 16:16
https://github.com/owncloud/contacts/commit/484fce0941e367cb984298bc4bc7a74f1505a5aa

**Comment by untitaker** [comment] 2015-08-31 16:57
@ is a safe character within the URI path. As far as PROPFIND is concerned,
ownCloud is behaving correctly.
