### ISSUE TITLE
Can't log to ownCloud

### ISSUE THREAD

**Issue by h3r0n** [bitfireAT/davdroid#610] opened 2015-08-18 10:32 UTC
Basically I can't log to ownCloud with davdroid. It stays this way for minutes ( http://i.imgur.com/W7urx2h.png ) until I see this message: "I/O Error Socket is closed".

It works if i try with other similar apps (like CalDAV-Sync). It also works on PC (GNOME/Evolution).

logcat: https://gist.github.com/anonymous/2089d22d81c5490226b5/raw/627c55a92b4d6b6dc33ef127425435e18cec5777/logcat.log

OwnCloud 8.1.1 on Arvixe
DAVdroid 0.8.3 from F-Droid
Xiaomi Mi2S
Android 5.1.1 (Cyanogenmod)

I also provided a test account
http://owncloud.h3ron.com
username: user
password: user

**Comment by devvv4ever** [comment] 2015-08-19 12:21
Did you have a connection in the past?

**Comment by h3r0n** [comment] 2015-08-19 12:34
Yes. It stopped working roughly less than a month ago.
The strange thing is that downgrading davdroid doesn't solve the problem. Still other (closed source) apps similar to davdroid do work flawlessly.

**Comment by devvv4ever** [comment] 2015-08-19 13:01
Other apps might have some workarounds for specific providers. We avoid it where we can, because they are a pain to maintain - also we've never had time to test owncube and arvixe (which seem to have the same backend, because at both providers the "Socket closed" error appeared at the same time). Currently I don't think this has something to do with DAVdroid, but we will test it ourselves soon to get more details on it!

**Comment by untitaker** [comment] 2015-08-19 13:30
@h3r0n What happens if you put a proxy such as mitmproxy inbetween?

I wonder whether this could be caused by an incorrect `Content-Length` header: https://issues.apache.org/jira/browse/HTTPCLIENT-908

**Comment by jochen314** [comment] 2015-08-25 19:40
I am a bit confused.
Your domain is http://owncloud.h3ron.com.
But there is a DNS SRV record for _carddavs._tcp.owncloud.h3ron.com (also for _caldav) pointing to https://caique.arvixe.com:2080/
To me it seems, that on caique.arvixe.com (185.21.132.34) no process is listening on port 2080.
But your owncloud server is running on owncloud.h3ron.com:80 (185.21.132.36:80), right?

**Comment by rfc2822** [comment] 2015-08-26 14:53
@h3r0n That's exactly the problem. The SRV records points to a service that doesn't run, this the timeout:

```

$ host -t SRV _carddavs._tcp.owncloud.h3ron.com
_carddavs._tcp.owncloud.h3ron.com has SRV record 0 0 2080 caique.arvixe.com.
$ nc caique.arvixe.com 2080
Ncat: Connection timed out.

```

Please contact your hoster and include this issue's URL.

I'll close the issue for now because it's not a DAVdroid problem. If there's anything new, please feel free to post again nevertheless.

**Closed by rfc2822** 2015-08-26 14:53 UTC
Labels: 3rd-party issue
