### ISSUE TITLE
Shared calendars in ownCloud (at least read-only) stopped syncing

### ISSUE THREAD

**Issue by mhspace** [bitfireAT/davdroid#597] opened 2015-08-07 01:48 UTC
Not sure exactly since which version it appeared. Something about 0.8 - 0.8.2

**Comment by Dark-Fenix** [comment] 2015-08-07 07:07
Hi, maybe I have the same problem.
I just updated my Xperia SP to Cyanogen 12.1 (Android 5.1) and setup a fresh davdroid sync with my ownCloud 8.1 server : my shared contacts and calendars (with other ownCloud users) are not synced with my phone. Tasks seems working.

**Comment by rfc2822** [comment] 2015-08-07 08:14
Thanks for your report. Please read [Reporting issues](https://github.com/bitfireAT/davdroid/blob/master/CONTRIBUTING.md#reporting-issues) and provide all information mentioned there, including **detailled steps to reproduce** the issue, **client and server software details**, and **[verbose logs](https://github.com/bitfireAT/davdroid/wiki/How-to-view-the-logs)**.

Is this a duplicate of #581?

**Comment by Dark-Fenix** [comment] 2015-08-07 08:45
I was collecting the logs, but you are right, it is the same than #581.
I fixed it on my owncloud server, waiting for an official update :)
Thanks !

**Comment by rfc2822** [comment] 2015-08-07 11:27
I'm happy that it now works for you, so I'm closing this issue.

**Closed by rfc2822** 2015-08-07 11:27 UTC
Labels: need info
