### ISSUE TITLE
Can't access shared collections

### ISSUE THREAD

**Issue by chris5560** [bitfireAT/davdroid#496] opened 2015-05-10 11:13 UTC
Hi,
on my Radicale server I set up 2 users (userA userB). They additional use a shared calendar. so my directory structure looks like:
[root]/userA/calendar.ics
[root]/userA/contacts.vcf
[root]/userB/calendar.ics
[root]/userB/contacts.vcf
[root]/shared/calendar.ics
each user has permission to it's own directory and to the shared folder.
Everything works fine from InfCloud and Thunderbird with Lightning and SoGo connector.
Whatever I enter into DAVdroid will only show the entry of the user that try to connect.
I tried: 
https://server:port/shared
https://server:port/shared/
https://server:port/shared/calendar.ics
https://server:port/shared/calendar.ics/

The shared Calender is never shown.
Thanks for support
Christian

**Comment by rfc2822** [comment] 2015-05-11 10:08
This is a duplicate of #249, please follow up there.

**Closed by rfc2822** 2015-05-11 10:08 UTC
Labels: duplicate
