### ISSUE TITLE
webcal support

### ISSUE THREAD

**Issue by ThomDietrich** [bitfireAT/davdroid#472] opened 2015-03-25 15:28 UTC
Some calendar sources provide webcal access, for example facebook with their export events functionality. Will davdroid support webcal in the near future?

Best, Thomas

**Comment by rfc2822** [comment] 2015-03-28 16:17
Duplicate of #36. WebCal is not related to CalDAV in any way, and DAVdroid is a CalDAV/CardDAV sync adapter.

**Closed by rfc2822** 2015-03-28 16:17 UTC
Labels: duplicate
