### ISSUE TITLE
Crash sync carddav with owncloud

### ISSUE THREAD

**Issue by chiisama** [bitfireAT/davdroid#448] opened 2015-02-18 20:20 UTC
2015-02-18 07:10:30,ERROR,AndroidRuntime,Unknown,FATAL EXCEPTION: SyncAdapterThread-1
Process: at.bitfire.davdroid:sync, PID: 16532
android.database.sqlite.SQLiteConstraintException: contacts.pinned may not be NULL (code 19)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:173)
	at android.database.DatabaseUtils.readExceptionWithOperationApplicationExceptionFromParcel(DatabaseUtils.java:160)
	at android.content.ContentProviderProxy.applyBatch(ContentProviderNative.java:519)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:377)
	at at.bitfire.davdroid.resource.LocalCollection.commit(LocalCollection.java:312)
	at at.bitfire.davdroid.resource.LocalAddressBook.commit(LocalAddressBook.java:148)
	at at.bitfire.davdroid.syncadapter.SyncManager.pullChanged(SyncManager.java:210)
	at at.bitfire.davdroid.syncadapter.SyncManager.synchronize(SyncManager.java:91)
	at at.bitfire.davdroid.syncadapter.DavSyncAdapter.onPerformSync(DavSyncAdapter.java:144)
	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)
02015-02-18 07:10:30,ERROR,AndroidRuntime,Unknown,FATAL EXCEPTION: SyncAdapterThread-1
Process: at.bitfire.davdroid:sync, PID: 16532
android.database.sqlite.SQLiteConstraintException: contacts.pinned may not be NULL (code 19)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:173)
	at android.database.DatabaseUtils.readExceptionWithOperationApplicationExceptionFromParcel(DatabaseUtils.java:160)
	at android.content.ContentProviderProxy.applyBatch(ContentProviderNative.java:519)
	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:377)
	at at.bitfire.davdroid.resource.LocalCollection.commit(LocalCollection.java:312)
	at at.bitfire.davdroid.resource.LocalAddressBook.commit(LocalAddressBook.java:148)
	at at.bitfire.davdroid.syncadapter.SyncManager.pullChanged(SyncManager.java:210)
	at at.bitfire.davdroid.syncadapter.SyncManager.synchronize(SyncManager.java:91)
	at at.bitfire.davdroid.syncadapter.DavSyncAdapter.onPerformSync(DavSyncAdapter.java:144)
	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:25Version 0.6.12
Carddav with owncloud 8.
Reproducable each time press sync carddav.

**Comment by rfc2822** [comment] 2015-02-18 20:22
Duplicate of #368, please follow up there.

**Closed by rfc2822** 2015-02-18 20:22 UTC
Labels: invalid
