### ISSUE TITLE
Can't add calndar/contact shared in Radicale Server

### ISSUE THREAD

**Issue by handfreezer** [bitfireAT/davdroid#492] opened 2015-05-01 18:53 UTC
When using Radicale Server configured to share a calendar in a collection which is not the one of the logged user, davdroid is only showing calendar and contacts of the logged user, but not shared one.

When I ask to have a look at http://IP/shared/ , the server is receiving a propfind request to /shared/ for prop:current-user-principal which is username, and then davdroid is requesting collection for /username/ instead of looking for /shared/ one as described in the URL.

Maybe, an option to choose the request or not of the prop could be added, or a cumulative list of the /shared/ and /username/ could be generated.

Contact me if needed.

**Comment by rfc2822** [comment] 2015-05-02 07:44
I guess this is a duplicate of #249, please follow up there.

Personally, I use Radicale with symlinks to make a shared calendar "my own", thus having it listed.

**Closed by rfc2822** 2015-05-02 07:44 UTC
Labels: duplicate

**Comment by handfreezer** [comment] 2015-05-03 13:25
Personnally, making a symlink do not allow you to manage authorisation. This is a "rustine" .

**Comment by rfc2822** [comment] 2015-05-03 13:57
> The right way is to create collections, and then defining rule of access depending of credentials.

With the only problem that there's no way to list those collections automatically, see #249.

**Comment by handfreezer** [comment] 2015-05-03 20:20
Yes, I agree with that, but I'm not good enough to know an other way to get a such good management of authorisation.

Maybe an other caldav/carddav server is listing all accessible collection by a user in its own collection as virtual calendar maybe, but I don't know a such server.

I agree what I'm asking for is for advanced user and configuration. That's why my patch on the fork I've done keep the default way of working of davdroid, but it could be changed as davdroid suggest a premptive login mode.

Cheers,
handfreezer
