### ISSUE TITLE
Kolab Now: no group support despite using CATEGORIES?

### ISSUE THREAD

**Issue by nebulon42** [bitfireAT/davdroid#438] opened 2015-02-05 18:21 UTC
This might be more a question than an issue, so feel free to point me towards more appropriate communication channels.

I'm a Kolab Now user and would love to use DAVdroid for syncing my contacts, but missing groups stop me from doing this. DAVdroid requires CATEGORIES, but after exporting my address book from the web interface I see them being used with the vCards.

Could you please clarify to me what it is that Kolab Now handles in a non-standard way or why no groups are supported? Thanks.

I have posted a similar question to Kolab Now Support and will report on their answer.

**Comment by devvv4ever** [comment] 2015-02-05 18:41
The problem is that there are multiple ways to support "groups". In vCard4 groups are fully specified. In vCard3 CATEGORIES _can_ be used as groups. However vCard3 does not officially support groups. DAVdroid complete support for vCard3 and very little vCard4 (only some properties). CATEGORIES from the vCard3 standard are supported by DAVdroid (this is why groups in owncloud work). Kolab Now uses another (valid!) way to support these (from vCard4). We have however alreadly looked at this more closely and it is not trivial to implement this... 

Some time DAVdroid will be fully compatible with vCard4 – this is a long time goal of us. So there will be also extended group support in the future. However, if someone is able to make a high quality patch for this, we'd appreciate to merge it to master (but I guess this will require structural changes).

**Comment by devvv4ever** [comment] 2015-02-05 18:43
Duplicate of #48

**Closed** 2015-02-05 18:46 UTC
Labels: duplicate
