### ISSUE TITLE
Radicale: can only choose calendar.ics

### ISSUE THREAD

**Issue by dannywillems** [bitfireAT/davdroid#559] opened 2015-06-22 12:28 UTC
Hi everyone.

I installed Radicale 0.9 on my server, and try to synchronize calendar with my smartphone on Android 5.1.1 with DavDroid 0.8.

I write the adress : http://HOST:5232/USERNAME/ with username and password, but I can only sync a calendar named 'calendar.ics' (synchronisation works with this one). I don't see other calendars which are on the server.

I tried with Thunderbird and I can access to the others calendars.

Can someone help me please ?

Thank you.

**Comment by rfc2822** [comment] 2015-06-24 10:32
Thanks for your report. This is a duplicate of #249, please follow up there.

**Closed by rfc2822** 2015-06-24 10:32 UTC
Labels: duplicate
