### ISSUE TITLE
Adding relationships to contacts on Android KitKat (Jiayu S3SW 4.4.4) makes DAVDroid (0.8.0 from F-Droid) crash

### ISSUE THREAD

**Issue by pierreghz** [bitfireAT/davdroid#569] opened 2015-07-02 10:24 UTC
If at least one contact has at least one relationship specified, the app crashes whenever it syncs. There’s a “RELATED” field in vCards so this should not happen, as far as I know.

**Comment by rfc2822** [comment] 2015-07-05 22:05
Can't reproduce that issue with CyanogenMod Android 4.4.4. Please provide detailed steps to reproduce (what relation to enter etc.).

**Comment by rfc2822** [comment] 2015-07-06 21:25
Duplicate of #547?

**Comment by rfc2822** [comment] 2015-07-06 23:56
Please check whether this issue is still present with DAVdroid 0.8.1.

**Comment by rfc2822** [comment] 2015-07-18 12:25
I guess this was a duplicate of #547, so I'll close this issue now. If this problem happens for DAVdroid 0.8.1+, please post here again.

**Closed by rfc2822** 2015-07-18 12:25 UTC
Labels: duplicate, need info
