### ISSUE TITLE
Unable to sync owncloud contacts

### ISSUE THREAD

**Issue by onny** [bitfireAT/davdroid#586] opened 2015-07-27 16:21 UTC
Hey,
I've owncloud 8.1.0 installed on my server together with owncloud app contacts in version 4.0. I have around 140 contacts stored on my OwnCloud installation. Unfortunately only a small part gets synced and I'm not sure if it's a problem with Owncloud, Davdroid or my Android phone.

In the adb log I can count 50 occurences of ```PRODID:-//Sabre//Sabre VObject 3.4.2``` so I guess only 50 contacts get synced.
Further I see some of these messages:
```
V/davdroid.URIUtils(12133): Normalized URI /remote.php/carddav/addressbooks/onny/default/20140308T125408.437fca1d03@owncloud.***.org.vcf -> /remote.php/carddav/addressbooks/onny/default/20140308T125408.437fca1d03@owncloud.***.org.vcf assuming that it was an URI or path name
D/davdroid.WebDavResource(12133): Processing multi-status element: https://owncloud.***.org/remote.php/carddav/addressbooks/onny/default/20140308T125408.437fca1d03@owncloud.***.org.vcf
```
And there are 93 occurences of 404 Not found: [...]
```
:propstat><d:prop><d:getetag>"66fd3ecf6ae75cb4af6d7fdf4fd7f0d3"</d:getetag></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat><d:propstat><d:prop><x3:getctag xmlns:x3="http://calendarserver.org/ns/"/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response><d:response><d:href>/remote.php/carddav/addressbooks/onny/default/8d3d15229f.vcf</d:href><d:propstat><d:prop><d:getetag>"9fed4bb14b2e9061a463ad9c03fc7ce6"</d:getetag></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat><d:propstat><d:prop><x3:getctag xmlns:x3="http://calendarserver.org/ns/"/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response><d:response><d:href>/remote.php/carddav/addressbooks/onny/default/eb10c29b96.vcf</d:href><d:propstat><d:prop><d:getetag>"9bb94425a71d157b0e63d0cb6a15baf0"</d:getetag></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat><d:propstat><d:prop><x3:getctag xmlns:x3="http://calendarserver.org/ns/"/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response><d:response><d:href>/remote.php/carddav/addressbooks/onny/default/b07ea24f8e.vcf<
```
How can I further debug this issue?
Best regards,
Jonas

**Comment by untitaker** [comment] 2015-07-27 17:31
This is a duplicate of #578.

**Comment by rfc2822** [comment] 2015-07-27 19:49
@untitaker, thanks for finding the duplicate.

@onny Please follow up in #578 and the linked OwnCloud issue report.

**Closed by rfc2822** 2015-07-27 19:49 UTC
Labels: duplicate
