### ISSUE TITLE
Syncing Calendar (0.6.10) ignores events with multiline properties (folding)

### ISSUE THREAD

**Issue by basc** [bitfireAT/davdroid#412] opened 2015-01-05 16:29 UTC
Calendar Events with a description or summary with multiple lines are ignored on syncing.

With DAVdroid 0.6.8 everything works fine.

Steps to reproduce:
Create an event with 64 or more characters in description or 68 or more chars in summary,
after syncing to the mobile device the event is missing.
An event with less then 64 chars in description and less then 68 chars in summary works well.

The first following event is displayed correct after syncinc, the second is missing
```
BEGIN:VEVENT
SUMMARY:Test with 63 characters
DESCRIPTION:123456789012345678901234567890123456789012345678901234567890123
END:VEVENT
BEGIN:VEVENT
SUMMARY:Test with 64 characters
DESCRIPTION:123456789012345678901234567890123456789012345678901234567890123
 4
END:VEVENT
```

Enviroment:
DAVdroid 0.6.10 from F-Droid (no error in 0.6.8)
Google Nexus 5 running Android 4.4.4 (cm-11-20141008-SNAPSHOT-M11)
OwnCloud 7 (hosted on virtual server)

**Comment by alwin148** [comment] 2015-01-06 08:54
Got the same issue, but first I thought it was related to shared calendars...
https://github.com/bitfireAT/davdroid/issues/405

**Comment by basc** [comment] 2015-01-06 13:38
Here is my ErrorLog. It is the same error as in #405 

```
E/davdroid.RemoteCollection(11836): Ignoring unparseable entity in multi-response
E/davdroid.RemoteCollection(11836): at.bitfire.davdroid.resource.InvalidResourceException: net.fortuna.ical4j.data.ParserException: Error at line 13:Illegal property [ 4]
```

The line that caused the error is
```
DESCRIPTION:123456789012345678901234567890123456789012345678901234567890123
 4
```

**Comment by rfc2822** [comment] 2015-01-06 16:49
Duplicate of #405, please follow up there.

**Closed by rfc2822** 2015-01-06 16:49 UTC
Labels: duplicate
