### ISSUE TITLE
Test DAVdroid on Android 5 [Lollipop]

### ISSUE THREAD

**Issue by devvv4ever** [bitfireAT/davdroid#360] opened 2014-11-11 08:23 UTC
Can someone test DAVdroid on Android 5? We don't have a device running this Android version, so it would be great to have it tested by someone.

**Comment by jelmer** [comment] 2015-02-08 22:48
FWIW I've been running davdroid without problems on a Nexus 5 and a Nexus 4 without problems.

**Comment by fabian-z** [comment] 2015-03-06 11:53
CM12 running on Moto G (falcon) here - unfortunately, DAVdroid stopped working for me after I updated both Android (5.0.2) and EGroupware (14.2). I used to run this setup (using older versions) for a long time and did not expect any problems. Since the new EGroupware version syncs fine with Lightning, etc. - this is why I suspect the problem may be DAVDroid on Android 5.

To rule out any problems in the F-Droid build I use I have built master for testing. CM privacy guard is disabled for DAVDroid. The setup process runs fine without errors (it also detects calendars and addressbooks). Also, DAVDroid does not throw any errors afterwards. I could not find any uncommon log entries, just the usual URL probing - the last thing I see is

```
I/davdroid.LocalCalendar( 9452): Inserting calendar: calendar_color=-3937682 canOrganizerRespond=1 sync_events=1 ownerAccount=testuser canModifyTimeZone=1 visible=1 account_type=bitfire.at.davdroid allowedAttendeeTypes=0,2,1,3 allowedAvailability=0,1,2 name=https://example.org/egroupware/groupdav.php/testuser/calendar/ allowedReminders=1 calendar_timezone=Europe/Berlin account_name=testuser calendar_access_level=700 calendar_displayName=Kalender Testnutzer -> content://com.android.calendar/calendars?account_name=testuser@example.org&account_type=bitfire.at.davdroid&caller_is_syncadapter=true
```

It does not sync any calendar or contact entries afterwards. Nothing in the logs, neither server nor logcat. Let me know if I should post full logcat. I would be glad about any hints - starting with, if I should open a seperate issue for this.

**Comment by rfc2822** [comment] 2015-03-06 12:02
> It does not sync any calendar or contact entries afterwards. Nothing in the logs, neither server nor logcat.

Is sync enabled? Did you try to force a sync process manually in the Settings? Is there "Sync calendars" and "Sync contacts"? Is there a status like "Last sync on …"?

**Comment by fabian-z** [comment] 2015-03-06 12:40
Sure, automatic data sync is enabled. It states "Synchronization: ON" for my account when I select the DAVDroid in Account settings (on the first page also offering me the DAVdroid-Website). If I then select the account, I see entries for calendar and contacts, each with (sometimes) active sync symbols and (always) active checkmarks.
Unfortunately, I see no possibility to manually force sync in the new Settings UI. Accessing the three-dot menu I only get the options to "Abort Sync" or "Remove Account". Also, there is no "Last sync on" status displayed. Let me know if I should provide screenshots or further debug info.

**Comment by fabian-z** [comment] 2015-03-06 15:40
I just tested with current DAVdroid 0.6.12 and the same EGroupware Server mentioned above but using CM11 (Android 4.4.4) instead of CM12, the sync works flawless for both contacts & calender. By now I'm pretty confident we are facing some kind of regression here..

**Comment by RobinWoodo** [comment] 2015-03-10 20:57
No problem on Nexus 9 (5.0.1) and latest baikal server. Works like a charm.

**Comment by dper** [comment] 2015-03-11 03:52
Running on Galaxy Note 4 (5.0.1) with OwnCloud on the server side. Smooth, no problems.

**Comment by rfc2822** [comment] 2015-03-28 22:08
Works here with (unofficial) Lollipop ROM (Galaxy S II), too, so I'll close this issue.

**Closed by rfc2822** 2015-03-28 22:08 UTC
Labels: question
