### ISSUE TITLE
DAVdroid doesn't understand America/Montevideo VTIMEZONE provided by Horde

### ISSUE THREAD

**Issue by fzipi** [bitfireAT/davdroid#489] opened 2015-04-28 18:24 UTC
There is a problem in synchronization when connecting to Horde CalDav.

Calendars are maitained on Horde, and subscriptions are from both Thunderbird (+Lightning), and DAVDroid. 

* Events created using Phone local calendar, all are sincronized to Horde and without problems to Thunderbird.
* Events created using Thunderbird or with Horde Web got correctly on server, but can't be sincronized with Phone

Errors seem similar to bitfireAT/davdroid#405

```
E/davdroid.RemoteCollection(29964): Ignoring unparseable entity in multi-response
E/davdroid.RemoteCollection(29964): at.bitfire.davdroid.resource.InvalidResourceException: net.fortuna.ical4j.data.ParserException: Error at line 314:null
E/davdroid.RemoteCollection(29964): 	at at.bitfire.davdroid.resource.Event.parseEntity(Event.java:147)
E/davdroid.RemoteCollection(29964): 	at at.bitfire.davdroid.resource.RemoteCollection.multiGet(RemoteCollection.java:112)
E/davdroid.RemoteCollection(29964): 	at at.bitfire.davdroid.syncadapter.SyncManager.pullNew(SyncManager.java:193)
E/davdroid.RemoteCollection(29964): 	at at.bitfire.davdroid.syncadapter.SyncManager.synchronize(SyncManager.java:90)
E/davdroid.RemoteCollection(29964): 	at at.bitfire.davdroid.syncadapter.DavSyncAdapter.onPerformSync(DavSyncAdapter.java:146)
E/davdroid.RemoteCollection(29964): 	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)
E/davdroid.RemoteCollection(29964): Caused by: net.fortuna.ical4j.data.ParserException: Error at line 314:null
E/davdroid.RemoteCollection(29964): 	at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:148)
E/davdroid.RemoteCollection(29964): 	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:210)
E/davdroid.RemoteCollection(29964): 	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:191)
E/davdroid.RemoteCollection(29964): 	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:179)
E/davdroid.RemoteCollection(29964): 	at at.bitfire.davdroid.resource.Event.parseEntity(Event.java:142)
E/davdroid.RemoteCollection(29964): 	... 5 more
E/davdroid.RemoteCollection(29964): Caused by: java.lang.NullPointerException
E/davdroid.RemoteCollection(29964): 	at net.fortuna.ical4j.model.component.Observance.getLatestOnset(Observance.java:169)
E/davdroid.RemoteCollection(29964): 	at net.fortuna.ical4j.model.TimeZone.getRawOffset(TimeZone.java:181)
E/davdroid.RemoteCollection(29964): 	at net.fortuna.ical4j.model.TimeZone.<init>(TimeZone.java:69)
E/davdroid.RemoteCollection(29964): 	at net.fortuna.ical4j.data.CalendarBuilder$ContentHandlerImpl.endComponent(CalendarBuilder.java:261)
E/davdroid.RemoteCollection(29964): 	at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.parse(CalendarParserImpl.java:412)
E/davdroid.RemoteCollection(29964): 	at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.access$1(CalendarParserImpl.java:376)
E/davdroid.RemoteCollection(29964): 	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(CalendarParserImpl.java:175)
E/davdroid.RemoteCollection(29964): 	at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:125)
E/davdroid.RemoteCollection(29964): 	... 9 more
```
Debug log can be found [here](https://gist.github.com/fzipi/e9c6354ef33f02c95925)

**Comment by rfc2822** [comment] 2015-04-28 19:27
There seems to be an error in the time zone definitions so ical4j throws a `NullPointerException`.

Can you please post the .ics contents of such an event?

**Comment by fzipi** [comment] 2015-04-28 19:36
Here are the contents of one unsynced event:
```
BEGIN:VCALENDAR
VERSION:2.0
X-WR-CALNAME:URI
PRODID:-//The Horde Project//Horde iCalendar Library//EN
BEGIN:VEVENT
DTSTART;TZID=America/Montevideo:20150430T130000
DTEND;TZID=America/Montevideo:20150430T150000
DTSTAMP:20150428T193234Z
UID:9cfc5f4f-d70c-4644-9668-1c5766383246
CREATED:20150424T193035Z
LAST-MODIFIED:20150427T140051Z
SUMMARY:Testing Event
CATEGORIES:Favorites
LOCATION:Testing
CLASS:PUBLIC
STATUS:CONFIRMED
TRANSP:OPAQUE
END:VEVENT
BEGIN:VTIMEZONE
TZID:America/Montevideo
BEGIN:STANDARD
DTSTART:18980628T000000
TZOFFSETFROM:-0344
TZOFFSETTO:-0344
TZNAME:MMT
END:STANDARD
BEGIN:STANDARD
TZOFFSETFROM:-0330
TZOFFSETTO:-0330
DTSTART:19231002T000000
TZNAME:UYHST
END:STANDARD
BEGIN:STANDARD
TZOFFSETFROM:-0330
TZOFFSETTO:-0330
TZNAME:UY-T
END:STANDARD
BEGIN:STANDARD
TZOFFSETFROM:-0330
TZOFFSETTO:-0330
TZNAME:UYHST
END:STANDARD
BEGIN:STANDARD
TZOFFSETFROM:-0330
TZOFFSETTO:-0330
DTSTART:19331029T000000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10;UNTIL=19351027T033000Z
TZNAME:UYHST
END:STANDARD
BEGIN:STANDARD
TZOFFSETFROM:-0330
TZOFFSETTO:-0330
DTSTART:19340331T233000
RRULE:FREQ=YEARLY;BYMONTH=3;BYMONTHDAY=25,26,27,28,29,30,31;BYDAY=1SA;UNTIL
 =19360330T030000Z
TZNAME:UY-T
END:STANDARD
BEGIN:STANDARD
TZOFFSETFROM:-0330
TZOFFSETTO:-0330
DTSTART:19361101T000000
TZNAME:UYHST
END:STANDARD
BEGIN:STANDARD
TZOFFSETFROM:-0330
TZOFFSETTO:-0330
DTSTART:19370328T000000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3;UNTIL=19410330T033000Z
TZNAME:UY-T
END:STANDARD
BEGIN:STANDARD
TZOFFSETFROM:-0330
TZOFFSETTO:-0330
DTSTART:19371031T000000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10;UNTIL=19401027T033000Z
TZNAME:UYHST
END:STANDARD
BEGIN:STANDARD
TZOFFSETFROM:-0330
TZOFFSETTO:-0330
DTSTART:19410801T000000
TZNAME:UYHST
END:STANDARD
BEGIN:STANDARD
TZOFFSETFROM:-0330
TZOFFSETTO:-0330
DTSTART:19420101T000000
TZNAME:UY-T
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:-0330
TZOFFSETTO:-0230
DTSTART:19421214T000000
TZNAME:UYST
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0300
TZOFFSETTO:-0300
DTSTART:19420101T000000
TZNAME:UY-T
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:-0300
TZOFFSETTO:-0200
DTSTART:19421214T000000
TZNAME:UYST
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0200
TZOFFSETTO:-0300
DTSTART:19430314T000000
TZNAME:UY-T
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:-0300
TZOFFSETTO:-0200
DTSTART:19590524T000000
TZNAME:UYST
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0200
TZOFFSETTO:-0300
DTSTART:19591115T000000
TZNAME:UY-T
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:-0300
TZOFFSETTO:-0200
DTSTART:19600117T000000
TZNAME:UYST
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0200
TZOFFSETTO:-0300
DTSTART:19600306T000000
TZNAME:UY-T
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:-0300
TZOFFSETTO:-0200
DTSTART:19650404T000000
RRULE:FREQ=YEARLY;BYMONTH=4;BYDAY=1SU;UNTIL=19670402T030000Z
TZNAME:UYST
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0200
TZOFFSETTO:-0300
DTSTART:19650926T000000
TZNAME:UY-T
END:STANDARD
BEGIN:STANDARD
TZOFFSETFROM:-0300
TZOFFSETTO:-0300
TZNAME:UY-T
END:STANDARD
BEGIN:STANDARD
TZOFFSETFROM:-0300
TZOFFSETTO:-0300
TZNAME:UYHST
END:STANDARD
BEGIN:STANDARD
TZOFFSETFROM:-0300
TZOFFSETTO:-0300
TZNAME:UY-T
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:-0300
TZOFFSETTO:-0200
DTSTART:19720424T000000
TZNAME:UYST
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0200
TZOFFSETTO:-0300
DTSTART:19720815T000000
TZNAME:UY-T
END:STANDARD
BEGIN:STANDARD
TZOFFSETFROM:-0300
TZOFFSETTO:-0300
DTSTART:19740310T000000
TZNAME:UYHST
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:-0300
TZOFFSETTO:-0200
DTSTART:19741222T000000
TZNAME:UYST
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0200
TZOFFSETTO:-0300
DTSTART:19761001T000000
TZNAME:UY-T
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:-0300
TZOFFSETTO:-0200
DTSTART:19771204T000000
TZNAME:UYST
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0200
TZOFFSETTO:-0300
DTSTART:19780401T000000
TZNAME:UY-T
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:-0300
TZOFFSETTO:-0200
DTSTART:19791001T000000
TZNAME:UYST
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0200
TZOFFSETTO:-0300
DTSTART:19800501T000000
TZNAME:UY-T
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:-0300
TZOFFSETTO:-0200
DTSTART:19871214T000000
TZNAME:UYST
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0200
TZOFFSETTO:-0300
DTSTART:19880314T000000
TZNAME:UY-T
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:-0300
TZOFFSETTO:-0200
DTSTART:19881211T000000
TZNAME:UYST
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0200
TZOFFSETTO:-0300
DTSTART:19890312T000000
TZNAME:UY-T
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:-0300
TZOFFSETTO:-0200
DTSTART:19891029T000000
TZNAME:UYST
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0200
TZOFFSETTO:-0300
DTSTART:19900304T000000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=1SU;UNTIL=19920301T030000Z
TZNAME:UY-T
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:-0300
TZOFFSETTO:-0200
DTSTART:19901021T000000
RRULE:FREQ=YEARLY;BYMONTH=10;BYMONTHDAY=21,22,23,24,25,26,27;BYDAY=1SU;UNTI
 L=19911027T030000Z
TZNAME:UYST
END:DAYLIGHT
BEGIN:DAYLIGHT
TZOFFSETFROM:-0200
TZOFFSETTO:-0200
DTSTART:19921018T000000
TZNAME:UYST
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0200
TZOFFSETTO:-0300
DTSTART:19930228T000000
TZNAME:UY-T
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:-0300
TZOFFSETTO:-0200
DTSTART:20040919T000000
TZNAME:UYST
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0200
TZOFFSETTO:-0300
DTSTART:20050327T020000
TZNAME:UY-T
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:-0300
TZOFFSETTO:-0200
DTSTART:20051009T020000
TZNAME:UYST
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0200
TZOFFSETTO:-0300
DTSTART:20060312T020000
TZNAME:UY-T
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:-0300
TZOFFSETTO:-0200
DTSTART:20061001T020000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=1SU
TZNAME:UYST
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0200
TZOFFSETTO:-0300
DTSTART:20070311T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYMONTHDAY=8,9,10,11,12,13,14;BYDAY=1SU
TZNAME:UY-T
END:STANDARD
END:VTIMEZONE
END:VCALENDAR
```

**Comment by rfc2822** [comment] 2015-04-28 20:20
On my Android device, there's no time zone "America/Montevideo". Can you try another time zone, maybe one that is also present on your Android device? You can try to create an event there and see which time zones are offered.

**Comment by fzipi** [comment] 2015-04-28 20:34
Here is an event created using phone's own calendar application, and pushed to Horde.
```
BEGIN:VCALENDAR
VERSION:2.0
X-WR-CALNAME:URI
PRODID:-//The Horde Project//Horde iCalendar Library//EN
BEGIN:VEVENT
DTSTART;TZID=America/Montevideo:20150429T180000
DTEND;TZID=America/Montevideo:20150429T190000
DTSTAMP:20150428T202847Z
UID:20150428T202813Z-15488@43b4481375972859
CREATED:20150428T202820Z
LAST-MODIFIED:20150428T202820Z
SUMMARY:Timezone test
CLASS:PUBLIC
STATUS:CONFIRMED
TRANSP:OPAQUE
END:VEVENT
BEGIN:VTIMEZONE
TZID:America/Montevideo
BEGIN:STANDARD
DTSTART:18980628T000000
TZOFFSETFROM:-0344
TZOFFSETTO:-0344
TZNAME:MMT
END:STANDARD
BEGIN:STANDARD
TZOFFSETFROM:-0330
TZOFFSETTO:-0330
DTSTART:19231002T000000
TZNAME:UYHST
END:STANDARD
BEGIN:STANDARD
TZOFFSETFROM:-0330
TZOFFSETTO:-0330
TZNAME:UY-T
END:STANDARD
BEGIN:STANDARD
TZOFFSETFROM:-0330
TZOFFSETTO:-0330
TZNAME:UYHST
END:STANDARD
BEGIN:STANDARD
TZOFFSETFROM:-0330
TZOFFSETTO:-0330
DTSTART:19331029T000000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10;UNTIL=19351027T033000Z
TZNAME:UYHST
END:STANDARD
BEGIN:STANDARD
TZOFFSETFROM:-0330
TZOFFSETTO:-0330
DTSTART:19340331T233000
RRULE:FREQ=YEARLY;BYMONTH=3;BYMONTHDAY=25,26,27,28,29,30,31;BYDAY=1SA;UNTIL
 =19360330T030000Z
TZNAME:UY-T
END:STANDARD
BEGIN:STANDARD
TZOFFSETFROM:-0330
TZOFFSETTO:-0330
DTSTART:19361101T000000
TZNAME:UYHST
END:STANDARD
BEGIN:STANDARD
TZOFFSETFROM:-0330
TZOFFSETTO:-0330
DTSTART:19370328T000000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3;UNTIL=19410330T033000Z
TZNAME:UY-T
END:STANDARD
BEGIN:STANDARD
TZOFFSETFROM:-0330
TZOFFSETTO:-0330
DTSTART:19371031T000000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10;UNTIL=19401027T033000Z
TZNAME:UYHST
END:STANDARD
BEGIN:STANDARD
TZOFFSETFROM:-0330
TZOFFSETTO:-0330
DTSTART:19410801T000000
TZNAME:UYHST
END:STANDARD
BEGIN:STANDARD
TZOFFSETFROM:-0330
TZOFFSETTO:-0330
DTSTART:19420101T000000
TZNAME:UY-T
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:-0330
TZOFFSETTO:-0230
DTSTART:19421214T000000
TZNAME:UYST
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0300
TZOFFSETTO:-0300
DTSTART:19420101T000000
TZNAME:UY-T
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:-0300
TZOFFSETTO:-0200
DTSTART:19421214T000000
TZNAME:UYST
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0200
TZOFFSETTO:-0300
DTSTART:19430314T000000
TZNAME:UY-T
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:-0300
TZOFFSETTO:-0200
DTSTART:19590524T000000
TZNAME:UYST
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0200
TZOFFSETTO:-0300
DTSTART:19591115T000000
TZNAME:UY-T
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:-0300
TZOFFSETTO:-0200
DTSTART:19600117T000000
TZNAME:UYST
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0200
TZOFFSETTO:-0300
DTSTART:19600306T000000
TZNAME:UY-T
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:-0300
TZOFFSETTO:-0200
DTSTART:19650404T000000
RRULE:FREQ=YEARLY;BYMONTH=4;BYDAY=1SU;UNTIL=19670402T030000Z
TZNAME:UYST
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0200
TZOFFSETTO:-0300
DTSTART:19650926T000000
TZNAME:UY-T
END:STANDARD
BEGIN:STANDARD
TZOFFSETFROM:-0300
TZOFFSETTO:-0300
TZNAME:UY-T
END:STANDARD
BEGIN:STANDARD
TZOFFSETFROM:-0300
TZOFFSETTO:-0300
TZNAME:UYHST
END:STANDARD
BEGIN:STANDARD
TZOFFSETFROM:-0300
TZOFFSETTO:-0300
TZNAME:UY-T
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:-0300
TZOFFSETTO:-0200
DTSTART:19720424T000000
TZNAME:UYST
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0200
TZOFFSETTO:-0300
DTSTART:19720815T000000
TZNAME:UY-T
END:STANDARD
BEGIN:STANDARD
TZOFFSETFROM:-0300
TZOFFSETTO:-0300
DTSTART:19740310T000000
TZNAME:UYHST
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:-0300
TZOFFSETTO:-0200
DTSTART:19741222T000000
TZNAME:UYST
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0200
TZOFFSETTO:-0300
DTSTART:19761001T000000
TZNAME:UY-T
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:-0300
TZOFFSETTO:-0200
DTSTART:19771204T000000
TZNAME:UYST
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0200
TZOFFSETTO:-0300
DTSTART:19780401T000000
TZNAME:UY-T
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:-0300
TZOFFSETTO:-0200
DTSTART:19791001T000000
TZNAME:UYST
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0200
TZOFFSETTO:-0300
DTSTART:19800501T000000
TZNAME:UY-T
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:-0300
TZOFFSETTO:-0200
DTSTART:19871214T000000
TZNAME:UYST
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0200
TZOFFSETTO:-0300
DTSTART:19880314T000000
TZNAME:UY-T
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:-0300
TZOFFSETTO:-0200
DTSTART:19881211T000000
TZNAME:UYST
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0200
TZOFFSETTO:-0300
DTSTART:19890312T000000
TZNAME:UY-T
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:-0300
TZOFFSETTO:-0200
DTSTART:19891029T000000
TZNAME:UYST
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0200
TZOFFSETTO:-0300
DTSTART:19900304T000000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=1SU;UNTIL=19920301T030000Z
TZNAME:UY-T
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:-0300
TZOFFSETTO:-0200
DTSTART:19901021T000000
RRULE:FREQ=YEARLY;BYMONTH=10;BYMONTHDAY=21,22,23,24,25,26,27;BYDAY=1SU;UNTI
 L=19911027T030000Z
TZNAME:UYST
END:DAYLIGHT
BEGIN:DAYLIGHT
TZOFFSETFROM:-0200
TZOFFSETTO:-0200
DTSTART:19921018T000000
TZNAME:UYST
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0200
TZOFFSETTO:-0300
DTSTART:19930228T000000
TZNAME:UY-T
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:-0300
TZOFFSETTO:-0200
DTSTART:20040919T000000
TZNAME:UYST
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0200
TZOFFSETTO:-0300
DTSTART:20050327T020000
TZNAME:UY-T
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:-0300
TZOFFSETTO:-0200
DTSTART:20051009T020000
TZNAME:UYST
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0200
TZOFFSETTO:-0300
DTSTART:20060312T020000
TZNAME:UY-T
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:-0300
TZOFFSETTO:-0200
DTSTART:20061001T020000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=1SU
TZNAME:UYST
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0200
TZOFFSETTO:-0300
DTSTART:20070311T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYMONTHDAY=8,9,10,11,12,13,14;BYDAY=1SU
TZNAME:UY-T
END:STANDARD
END:VTIMEZONE
END:VCALENDAR
```

**Comment by fzipi** [comment] 2015-04-28 20:45
TimeZone [America/Montevideo](http://en.wikipedia.org/wiki/America/Montevideo) is part of the tz database. At least from [ical4j documentation](https://github.com/ical4j/ical4j/wiki/Timezones#zoneinfo) i'm assuming it is very well supported.

**Comment by rfc2822** [comment] 2015-04-28 22:23
Android's calendar storage doesn't use ical4j (only DAVdroid does), so it can only process time zones which are known in the Android system.

Could you please verify that America/Montevideo is not selectable in your calendar app and try a time zone that is present in your Android system?

**Comment by fzipi** [comment] 2015-04-29 13:40
The string displayed for the zone in calendar is 'Uruguay Standard Time'.

**Comment by fzipi** [comment] 2015-04-29 13:49
As I understand, 'America/Montevideo' is [understood by android](http://developer.android.com/reference/java/util/TimeZone.html#getTimeZone%28java.lang.String%29). It should be very easy to create a program that iterates over TimeZone list printing its Name and/or Ids to verify this.

**Comment by rfc2822** [comment] 2015-04-29 15:12
DAVdroid logs contain the output of the function that searches through the Android time zones. Could you  please [provide logs](https://github.com/bitfireAT/davdroid/wiki/How-to-view-the-logs)?

**Comment by fzipi** [comment] 2015-04-29 15:16
Debug logs went on the first comment, on this [gist](https://gist.github.com/fzipi/e9c6354ef33f02c95925)

**Comment by rfc2822** [comment] 2015-04-29 15:19
Sorry, didn't see that. I'm now able to reproduce the issue with our testing device and will have a look.

**Comment by fzipi** [comment] 2015-04-29 15:22
Excellent. I think this [other gist](https://gist.github.com/arpit/1035596) is old, but there is already listing android timezone ids and 'America/Montevideo' seems to be there.

**Comment by rfc2822** [comment] 2015-04-29 15:27
It seems like ical4j can't parse the VTIMEZONE given by Horde. The one bundled with ical4j works.

Do you know if there's something like a VTIMEZONE validator out there? Do you think it's possible that the Horde VTIMEZONE is incorrect or that the problem is caused by ical4j and for what reason?

**Comment by rfc2822** [comment] 2015-04-29 16:31
The problem are  the time zone components which don't have DTSTART, TZOFFSETFROM **and** TZOFFSETTO, for instance:

```
BEGIN:STANDARD
TZOFFSETFROM:-0330
TZOFFSETTO:-0330
TZNAME:UY-T
END:STANDARD
```

According to [RFC 5545 3.6.5](http://tools.ietf.org/html/rfc5545#section-3.6.5), a `standardc` time zone component **must** have a DTSTART value. Such time zone component without DTSTART wouldn't make any sense because you can't know when this `UY-T` time with-0330 offset is defined.

ical4j expects exactly this (a DTSTART) and throws an exception.

So, the VTIMEZONE provided by Horde is invalid. I don't know whether it's generated by Horde or uploaded by another client and just taken over by Horde.

**Comment by rfc2822** [comment] 2015-05-12 16:50
Can you please try to contact Horde people and report this issue?

**Comment by fzipi** [comment] 2015-05-12 17:21
I created [this bug report](https://bugs.horde.org/ticket/13972). If you like I could post any resolution there on this one.

**Comment by rfc2822** [comment] 2015-05-12 18:09
Thanks - could you please add a link to this issue to the Horde bug report?

I'll close the issue here.

**Closed by rfc2822** 2015-05-12 18:09 UTC
Labels: 3rd-party issue, invalid
