### ISSUE TITLE
Can't write contactname - it changes to nullnull

### ISSUE THREAD

**Issue by ghost** [bitfireAT/davdroid#444] opened 2015-02-15 22:56 UTC
Contactsync between Synology NAS and Xperia Z3 (Android 4.4.4) does not work properly:
If I create a new contact on the phone, the "name" field won't be saved. After syncing it is displayed as "nullnull"

**Comment by rfc2822** [comment] 2015-02-15 23:14
Thanks for your report. Please read [Reporting issues](https://github.com/bitfireAT/davdroid/blob/master/CONTRIBUTING.md#reporting-issues) and provide all information mentioned there, including **detailled steps to reproduce** the issue, **client and server software details**, and **[verbose logs](https://github.com/bitfireAT/davdroid/wiki/How-to-view-the-logs)**.

Where is it displayed? On the phone?

**Comment by fabif** [comment] 2015-02-16 14:03
Phone: Xperia z3, original rom android 4.4.4
Client: Davdroid from googlePlay, V0.6.12
Server: Synology DSM 5.1-5022 Update 2 with Carddav Server 5.2.0-0021

Steps to reproduce the Problem:
Connect to DS via LanIp without Ssl (to keep it simple). Create a new contact on the phone with just a name and telephone-nr. In the DAVDroid Account.
After saving the contact details will be shown, but there is no name. If you edit the contact, the name field is empty.
After syncing the name field will be changed to: "nullnull" - On the phone and server.

Contacts which are downloaded from the server will have a name, but it is not possible to change it on the phone. Every other field is changeable.

It seems, that the contact Editor cant save values in the name field. A friend tried the same steps with his motorola razr xt910, Android 4.1.2, and had the same issue.

**Comment by rfc2822** [comment] 2015-02-16 14:52
@fabif Would it be possible for you to provide a test account so that we can reproduce and identify the problem?

**Comment by fabif** [comment] 2015-02-17 21:04
Is it possible to write you a private message? I do not want to post login data publicly...

**Comment by devvv4ever** [comment] 2015-02-17 22:06
Sure, please send it to play@bitfire.at. Only the developers will receive this email. Thank you!

**Comment by rfc2822** [comment] 2015-03-02 12:08
@fabif Did you already contact us? Is the issue still present?

**Comment by rfc2822** [comment] 2015-04-30 12:59
Closing because of missing user response.

**Closed by rfc2822** 2015-04-30 12:59 UTC
Labels: need info

**Comment by bummi2k** [comment] 2015-05-03 20:00
This probably a Sony "feature". I had the same issue using the CardDAV app from the play store.
My setup:
Phone: Sony Z3 compact with Android 5.0.2
Client: CardDAV 0.4.13
Server: Horde 5.2.6
When you are creating or editing a contact on the phone, you can enter name and some "phonetic" names. Than the name will by ignored causing a "nullnull" name after syncing.
But if you hit the extension button (arrow down symbol at the name fields) you can enter a proper first name and last name. After that syncing worked for me.
I don't know DAVdroid, but let me know if this works for you.
The Sony phone seems to be confused with all the naming features of carddav.

**Comment by uzadow** [comment] 2015-08-28 11:43
I can confirm that I have this issue as well on my Sony Z3. bummi2k's workaround works for me as well, but a real fix would make the app a lot easier to use for Sony users.
