### ISSUE TITLE
Editable server information

### ISSUE THREAD

**Issue by hitam4450** [bitfireAT/davdroid#612] opened 2015-08-18 15:28 UTC
Currently i use davdroid v 0.83 with OC 8.1.1 and all calendar items synchronizing smoothly.
For adding account i used the "By URL and account name" option.

However, i have to change the fixed IP-address of the server and now  sync is no more possible, unless I delete the account (and loose all date) and create the same account with the different IP-Address.
In the new location I started a new instance of OC without any calendar data.

Could you please make the account details "editable" after creating an account, to be able to make adjustments in case e.g. the server address changes, without loosing any data!

Thanks & regards, hitam4450

**Comment by devvv4ever** [comment] 2015-08-18 22:24
We understand the necessity for this and have it on our timeline. It will come to DAVdroid when we reached a status where the core components such as the sync processor will no longer be changed much.

duplicate of #219

**Closed by devvv4ever** 2015-08-18 22:24 UTC
