### ISSUE TITLE
RDATE: missing first instance and time zone ignored

### ISSUE THREAD

**Issue by jspricke** [bitfireAT/davdroid#340] opened 2014-10-22 12:14 UTC
Hi,

Davdroid ignores the time zone information in an RDATE. Also it ignores the DTSTART as the first event date. Example:
```BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Radicale//NONSGML Radicale Server//EN
BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:STANDARD
DTSTART:20001029T030000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
TZNAME:CET
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:20000326T020000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3
TZNAME:CEST
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
UID:1:-191507020323643003
DTSTART;TZID=Europe/Berlin:20141015T160000
DTEND;TZID=Europe/Berlin:20141015T160000
RDATE;TZID=Europe/Berlin:20141022T160000,20141029T160000,20141105T160000
SUMMARY:Test
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:Test
TRIGGER:-PT10M
END:VALARM
END:VEVENT
END:VCALENDAR
```

**Comment by rfc2822** [comment] 2015-05-02 09:51
1. Regarding the time zones: DAVdroid now writes the TZID (if set) to the Calendar provider, causing the recurring instances to have correct time. The time zone are not shown in the calendar due Android recurrence processing, but the time should be correct.
1. Regarding the missing first instance: Android's [RecurrenceProcessor](https://android.googlesource.com/platform/frameworks/opt/calendar/+/master/src/com/android/calendarcommon2/RecurrenceProcessor.java) method expand() is responsible for expanding the recurrence. It's called with both DTSTART and RDATE, but it only returns the RDATE recurrences. [CalendarInstancesHelper](https://android.googlesource.com/platform/packages/providers/CalendarProvider/+/master/src/com/android/providers/calendar/CalendarInstancesHelper.java) takes

* DTSTART in case of non-recurring events,
* the result of `RecurrenceProcessor.expand(DTSTART,RDATE)` (which does not include the DTSTART instance) in case of recurring events

as the instance date(s), so it misses the DTSTART instance in case of recurring events.

So I consider this an Android bug; I guess it's caused by a non-precise specification of whether``RecurrenceProcessor.expand(DTSTART,RDATE)` shall return the first instance or not. Because of this missing specification, wrong assumptions are made in `CalendarInstancesHelper`, causing this bug.

**Comment by rfc2822** [comment] 2015-05-02 10:00
Please also follow up at https://code.google.com/p/android/issues/detail?id=171292

**Comment by rfc2822** [comment] 2015-05-02 10:02
As the time zone issue has been fixed in DAVdroid, I'll consider this issue as a third-party bug from now on.

**Comment by jspricke** [comment] 2015-05-03 20:10
Hi rfc2822, thanks for taking care of this!

**Comment by rfc2822** [comment] 2015-05-03 20:12
:) Let's see whether this issue will be fixed in Android.

**Closed** 2015-05-03 20:12 UTC
Labels: 3rd-party issue

**Comment by jspricke** [comment] 2015-05-03 20:15
For reference, I've worked around these two here: https://github.com/jspricke/python-remind/blob/master/remind.py#L165

**Comment by rfc2822** [comment] 2015-05-09 11:41
Please see also https://code.google.com/p/android/issues/detail?id=172442
