### ISSUE TITLE
Error sync Posteo-calendar

### ISSUE THREAD

**Issue by paifgx** [bitfireAT/davdroid#435] opened 2015-01-28 20:42 UTC
I also have a problem with calender sync with Posteo (adressbook works). via logcat:

```
01-28 20:14:49.270  12742-12760/at.bitfire.davdroid:sync E/JavaBinder﹕ !!! FAILED BINDER TRANSACTION !!!
01-28 20:14:49.270  12742-12760/at.bitfire.davdroid:sync E/davdroid.DavSyncAdapter﹕ Local storage (content provider) exception
    at.bitfire.davdroid.resource.LocalStorageException: Couldn't access local content provider
            at at.bitfire.davdroid.resource.LocalCollection.commit(LocalCollection.java:315)
            at at.bitfire.davdroid.syncadapter.SyncManager.pullNew(SyncManager.java:196)
            at at.bitfire.davdroid.syncadapter.SyncManager.synchronize(SyncManager.java:90)
            at at.bitfire.davdroid.syncadapter.DavSyncAdapter.onPerformSync(DavSyncAdapter.java:144)
            at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)
     Caused by: android.os.TransactionTooLargeException
            at android.os.BinderProxy.transact(Native Method)
            at android.content.ContentProviderProxy.applyBatch(ContentProviderNative.java:517)
            at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:377)
            at at.bitfire.davdroid.resource.LocalCollection.commit(LocalCollection.java:312)
            at at.bitfire.davdroid.syncadapter.SyncManager.pullNew(SyncManager.java:196)
            at at.bitfire.davdroid.syncadapter.SyncManager.synchronize(SyncManager.java:90)
            at at.bitfire.davdroid.syncadapter.DavSyncAdapter.onPerformSync(DavSyncAdapter.java:144)
            at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)
```

**Comment by rfc2822** [comment] 2015-01-28 21:57
Duplicate of #274?

**Comment by devvv4ever** [comment] 2015-02-05 18:50
@paifgx Does this problem persist?

**Comment by paifgx** [comment] 2015-02-05 21:08
Yes, problem still persist.

**Comment by rfc2822** [comment] 2015-02-07 12:21
@paifgx Is it a duplicate of #274?

**Comment by paifgx** [comment] 2015-02-08 22:32
Don't think so. But not sure.
koaoala mean thats a Posteo problem (!?) https://github.com/bitfireAT/davdroid/issues/392#issuecomment-71915538

**Comment by rfc2822** [comment] 2015-02-09 15:51
Please read [Reporting issues](https://github.com/bitfireAT/davdroid/blob/master/CONTRIBUTING.md#reporting-issues) and provide all information mentioned there, including **detailled steps to reproduce** the issue, **client and server software details**, and **[verbose logs](https://github.com/bitfireAT/davdroid/wiki/How-to-view-the-logs)**.

**Comment by paifgx** [comment] 2015-02-09 15:51
I have tested what happens if i create only a entry through Posteo lone. Lo and behold! It works without any errors. It seems to be a problem with sync Android <-> Posteo <-> Thunderbird.

**Comment by rfc2822** [comment] 2015-02-09 16:08
> Caused by: android.os.TransactionTooLargeException

Means that there's a single entry (event) with too many sub-rows (attendees, for instance).

**Comment by rfc2822** [comment] 2015-03-02 12:06
Any news on this?

**Closed** 2015-03-06 12:03 UTC
Labels: need info
