### ISSUE TITLE
Not all Contacts from ownCloud are shown in the Android Contacts-App

### ISSUE THREAD

**Issue by Tronde** [bitfireAT/davdroid#624] opened 2015-08-27 12:44 UTC
Hello.

I installed davdroid from the f-droid repository. I configured the connection to my ownCloud to sync contacts, calendars and tasks. All syncs are fine but the contacts sync.

When I look in the Android contacts app I can see that my contacts are being synced. New contacts were added to the app. But at some point the synced contacts disappear. After the syncing process the contact app shows only four contacts. I figured out, that there is something special about these for contacts. All four have in common that I added them on my iPhone and synced them to my ownCloud.

But I have no idea why all the other contacts aren't shown after the sync finished.

Here are some information about my system:

Tablet: Nexus 7 (Edition 2012)
Android Version: 5.1.1
Build Number: LMY47V
Kernel-Version: 3.1.10-gf5d7b8b

You could find the log at [this link.](https://gist.github.com/Tronde/ce11052743c1595cd041)

**Comment by devvv4ever** [comment] 2015-08-27 13:02
Hi, 
this is probably the issue that affects many OC users currently. There is a bug in your OC, you need to adjust only a single line in a php file. Please look here #578 

There is already a fix for it but I don't know when OC makes a new release.

I'm closing this since it is a duplicate of #578

**Closed by devvv4ever** 2015-08-27 13:02 UTC
