### ISSUE TITLE
First Sync error

### ISSUE THREAD

**Issue by Alby1987** [bitfireAT/davdroid#532] opened 2015-06-04 15:38 UTC
I'm trying to use davdroid for using a carddav server in a android. We use high-res photo on our server (we need that), but the transaction buffer is only 1 MB, and it throws the famous LocalStorageException. We use the last binary versions 0.8.0 . There is a workaround for importing without photos, or just some contacts at a time (and not the whole).

Thank you

**Comment by untitaker** [comment] 2015-06-04 15:55
Same as #291. Unfortunately there is no such workaround...

**Comment by rfc2822** [comment] 2015-06-07 00:54
Thanks for your report, but this is a duplicate of #230. Please follow up there.

**Closed by rfc2822** 2015-06-07 00:54 UTC
Labels: duplicate
