### ISSUE TITLE
Support self signed certificates out of the box

### ISSUE THREAD

**Issue by CannyDuck** [bitfireAT/davdroid#437] opened 2015-02-03 19:59 UTC
Please support the use of self signed certificates without required workarounds. Other apps like CalDAV Sync (https://play.google.com/store/apps/details?id=org.dmfs.caldav.lib) show an advice the user have to confirm, before doing the sync, so no workarounds requred.

**Comment by dper** [comment] 2015-02-03 22:42
This issue has been raised before.  See <https://github.com/bitfireAT/davdroid/issues/3>.  The short answer is that you can use CAdroid to import your own certificates.

In point of fact, if DAVdroid were to support self-signed certificates, DAVdroid itself would be doing a workaround of Android's certificate management process.

**Comment by rfc2822** [comment] 2015-02-03 22:49
Duplicate of #3, please follow up there.

I have recently seen a certificate without CA flag that could be imported and used with DAVdroid in Android 4.4, so when I find time, there might be a CAdroid update that allows certificates without CA flag to be imported in certain Android versions. That would greatly improve user experience for DAVdroid users, too.

For more information, please see in #3, https://davdroid.bitfire.at/faq/entry/importing-a-certificate, and http://cadroid.bitfire.at/.

**Closed by rfc2822** 2015-02-03 22:49 UTC
Labels: duplicate
