### ISSUE TITLE
Soft HTTP error 302

### ISSUE THREAD

**Issue by zstephen** [bitfireAT/davdroid#534] opened 2015-06-05 07:49 UTC
I am running DAVdroid 0.8 with Zimbra 8.6.0_GA_1162 (build 20150225174718) and am getting a sync error on my LP 5.1.1 device. I'm not quite sure where to start my troubleshooting, but I did a debug recently and found some possibly relevant detail.

06-04 22:06:58.350    6692-7096/? V/davdroid.URIUtils﹕ Normalized URL 20150604T120658Z-6692_518a4a2985156.ics -> 20150604T120658Z-6692_518a4a2985156.ics
06-04 22:07:02.100    6692-7096/? E/davdroid.DavRedirectStrategy﹕ Received redirection without Location header, ignoring
06-04 22:07:02.104    6692-7096/? W/davdroid.DavSyncAdapter﹕ Soft HTTP error 302 (Android will try again later)
    at.bitfire.davdroid.webdav.HttpException: 302 Found
            at at.bitfire.davdroid.webdav.WebDavResource.checkResponse(WebDavResource.java:431)
            at at.bitfire.davdroid.webdav.WebDavResource.checkResponse(WebDavResource.java:405)
            at at.bitfire.davdroid.webdav.WebDavResource.put(WebDavResource.java:382)
            at at.bitfire.davdroid.resource.RemoteCollection.add(RemoteCollection.java:180)
            at at.bitfire.davdroid.syncadapter.SyncManager.pushNew(SyncManager.java:143)
            at at.bitfire.davdroid.syncadapter.SyncManager.synchronize(SyncManager.java:49)
            at at.bitfire.davdroid.syncadapter.DavSyncAdapter.onPerformSync(DavSyncAdapter.java:146)
            at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)
06-04 22:07:02.104    6692-7096/? I/davdroid.DavSyncAdapter﹕ Sync complete for com.android.calendar
06-04 22:07:02.173    6692-6692/? D/davdroid.DavSyncAdapter﹕ Closing httpClient
06-04 22:07:02.177      709-728/? D/SyncManager﹕ failed sync operation xxxx@xxxx.com.au u0 (bitfire.at.davdroid), com.android.calendar, LOCAL, currentRunTime 173275, reason: 10002, SyncResult: stats [ numIoExceptions: 1]

**Comment by rfc2822** [comment] 2015-06-05 09:38
Thanks for your report. This is a duplicate of #478 and Zimbra bug, please follow up at the Zimbra forums post linked there.

**Closed by rfc2822** 2015-06-05 09:38 UTC
Labels: duplicate
