### ISSUE TITLE
Calendar sync results in Bad Request 400

### ISSUE THREAD

**Issue by gofabian** [bitfireAT/davdroid#562] opened 2015-06-24 10:17 UTC
I synchronize 2 calendars with my Posteo account. The synchronization does not work anymore for 1 month. The synchronization always results in the HTTP error 400 Bad Request.

DAVdroid 0.8.0 from Play Store
DAVdroid JB Workaround 1.0
Android 4.4.4
Samsung Galaxy Alpha (SM-G850F)
CalDAV server: Posteo.de

Logfile: https://gist.github.com/gofabian/e62362918cccfa12a987

Thanks a lot for your support!
Fabian

**Comment by rfc2822** [comment] 2015-06-24 10:31
Is this related to recurring events, see #523?

**Comment by gofabian** [comment] 2015-06-24 11:35
No, I cannot see the same error message. The server does not respond a certain reason:

D/Wire    (13260): http-outgoing-0 << "HTTP/1.1 400 Bad request[\r][\n]"
D/Wire    (13260): http-outgoing-0 << "Date: Wed, 24 Jun 2015 10:15:34 GMT[\r][\n]"
D/Wire    (13260): http-outgoing-0 << "Server: Apache[\r][\n]"
D/Wire    (13260): http-outgoing-0 << "X-Powered-By: PHP/5.4.35-0+deb7u2[\r][\n]"
D/Wire    (13260): http-outgoing-0 << "Connection: close[\r][\n]"
D/Wire    (13260): http-outgoing-0 << "Transfer-Encoding: chunked[\r][\n]"
D/Wire    (13260): http-outgoing-0 << "Content-Type: application/xml; charset=utf-8[\r][\n]"
D/Wire    (13260): http-outgoing-0 << "[\r][\n]"

**Comment by rfc2822** [comment] 2015-06-24 16:20
However, it seems to be related to recurring events:

```
D/Wire    (13260): http-outgoing-0 >> "BEGIN:VEVENT[\r][\n]"
D/Wire    (13260): http-outgoing-0 >> "DTSTAMP:20150624T101554Z[\r][\n]"
D/Wire    (13260): http-outgoing-0 >> "UID:20150408T070427Z-27766@92a0e4fff7a79fb6[\r][\n]"
D/Wire    (13260): http-outgoing-0 >> "DTSTART;TZID=Europe/Berlin:20150408T160000[\r][\n]"
D/Wire    (13260): http-outgoing-0 >> "DURATION:PT10800S[\r][\n]"
D/Wire    (13260): http-outgoing-0 >> "RRULE:FREQ=WEEKLY;WKST=MO;UNTIL=20150624T135959Z;BYDAY=WE[\r][\n]"
D/Wire    (13260): http-outgoing-0 >> "SUMMARY:After-Work-Radeln [\r][\n]"
D/Wire    (13260): http-outgoing-0 >> "STATUS:CONFIRMED[\r][\n]"
D/Wire    (13260): http-outgoing-0 >> "ORGANIZER:mailto:username@posteo.de[\r][\n]"
D/Wire    (13260): http-outgoing-0 >> "LAST-MODIFIED:20150624T101554Z[\r][\n]"
D/Wire    (13260): http-outgoing-0 >> "END:VEVENT[\r][\n]"
D/Wire    (13260): http-outgoing-0 >> "BEGIN:VEVENT[\r][\n]"
D/Wire    (13260): http-outgoing-0 >> "DTSTAMP:20150624T101554Z[\r][\n]"
D/Wire    (13260): http-outgoing-0 >> "UID:20150413T095838Z-482@92a0e4fff7a79fb6[\r][\n]"
D/Wire    (13260): http-outgoing-0 >> "RECURRENCE-ID:20150415T140000Z[\r][\n]"
D/Wire    (13260): http-outgoing-0 >> "DTSTART;TZID=Europe/Berlin:20150415T160000[\r][\n]"
D/Wire    (13260): http-outgoing-0 >> "DTEND;TZID=Europe/Berlin:20150415T190000[\r][\n]"
D/Wire    (13260): http-outgoing-0 >> "SUMMARY:After-Work-Radeln [\r][\n]"
D/Wire    (13260): http-outgoing-0 >> "STATUS:CANCELLED[\r][\n]"
D/Wire    (13260): http-outgoing-0 >> "LAST-MODIFIED:20150624T101554Z[\r][\n]"
D/Wire    (13260): http-outgoing-0 >> "UID:20150408T070427Z-27766@92a0e4fff7a79fb6[\r][\n]"
D/Wire    (13260): http-outgoing-0 >> "END:VEVENT[\r][\n]"
D/Wire    (13260): http-outgoing-0 >> "BEGIN:VEVENT[\r][\n]"
D/Wire    (13260): http-outgoing-0 >> "DTSTAMP:20150624T101554Z[\r][\n]"
D/Wire    (13260): http-outgoing-0 >> "RECURRENCE-ID:20150520T140000Z[\r][\n]"
D/Wire    (13260): http-outgoing-0 >> "DTSTART;TZID=Europe/Berlin:20150520T160000[\r][\n]"
D/Wire    (13260): http-outgoing-0 >> "DTEND;TZID=Europe/Berlin:20150520T190000[\r][\n]"
D/Wire    (13260): http-outgoing-0 >> "SUMMARY:After-Work-Radeln [\r][\n]"
D/Wire    (13260): http-outgoing-0 >> "STATUS:CANCELLED[\r][\n]"
D/Wire    (13260): http-outgoing-0 >> "LAST-MODIFIED:20150624T101554Z[\r][\n]"
D/Wire    (13260): http-outgoing-0 >> "UID:20150408T070427Z-27766@92a0e4fff7a79fb6[\r][\n]"
D/Wire    (13260): http-outgoing-0 >> "END:VEVENT[\r][\n]"
```

Can you please verify that this only happens for recurring events? In this case, it would be a duplicate of #523.

**Comment by gofabian** [comment] 2015-06-25 14:18
I will check that.

**Comment by rfc2822** [comment] 2015-07-05 22:22
Please follow up in #523.

**Closed by rfc2822** 2015-07-05 22:22 UTC
Labels: need info
