### ISSUE TITLE
Re-discover available calendars

### ISSUE THREAD

**Issue by Dark-Fenix** [bitfireAT/davdroid#540] opened 2015-06-08 12:47 UTC
Hi,

I don't know if it is a normal behaviour or if the "problem" is already reported elsewhere, but here's the thing : 

I sync some calendars with my ownCloud 8 instance. When I set up davdroid for the first time on my Androphone, I can select all the calendars I want to sync.
But, if I add a new calendar on ownCloud (or a Task list), I would like to add it to the sync : is there any way to do this through davdroid ? When I go to the account settings, I see no option to do so, and when I go to the calendar Android app, I only see the list of calendar I currently sync, not the server's new ones.

Thanks !

**Comment by rfc2822** [comment] 2015-06-08 13:13
Duplicate of #219, please follow up there.

**Closed by rfc2822** 2015-06-08 13:13 UTC
Labels: duplicate
