### ISSUE TITLE
Edit or add new calendar

### ISSUE THREAD

**Issue by holzhannes** [bitfireAT/davdroid#494] opened 2015-05-07 13:30 UTC
If I add an new calendar in owncloud this calendar is not getting synced to my device. The only solution is to delete the DavDroid account and create a new one. Is it possible to edit the synced calendars after the DavDroid account is created?

Thank you very much for this very good App!

**Comment by rfc2822** [comment] 2015-05-07 19:51
Thanks for your report, but it's a duplicate of #219. Please follow up there.

**Closed by rfc2822** 2015-05-07 19:51 UTC
Labels: duplicate
