### ISSUE TITLE
sync error

### ISSUE THREAD

**Issue by forght** [bitfireAT/davdroid#505] opened 2015-05-18 13:54 UTC
Since some time( probably V0.7.6) DAVdroid reports sync errors. It started with problems with the contacts but since V0.7.7 contact sync woks but the calendar won´t synchronize( last time 13.05)

Notification:
_@posteo.de:
at.bitfire.davdroid.webdav.HttpException: 400 Bad request at at.bitfire.davdroid.webdav.WebDavResource.checkResponse(WebDavResource.java:419)
at...

**Comment by ddorian1** [comment] 2015-05-23 22:22
I also get this error for calendar synchronisation since 0.7.7 (with owncloud 8.0.3), but it seems to work nevertheless (I haven't tested it thoroughly though).
Here are some logs, let me know if I can provide some other information:
https://jschwab.org/davDroid_log.txt

**Comment by rfc2822** [comment] 2015-05-25 18:33
@ddorian1 Thanks for the log, but it doesn't contain network logs. Please set log.tag.Wire to and log.tag.HttpClient to VERBOSE as [described here](https://github.com/bitfireAT/davdroid/wiki/How-to-view-the-logs).

**Comment by gour** [comment] 2015-05-26 10:05
Same issue here  - 0.7.7 and oC-8.x, but workaround mentioned in #502 solved it...

**Comment by ddorian1** [comment] 2015-05-26 10:39
Ok, here is a verbose logcat: https://jschwab.org/davDroid_log_verbose.txt

**Comment by ddorian1** [comment] 2015-05-29 20:52
FYI: for me the problem persists with 0.8 and reinstallation of davdroid doesn't help neither.

**Comment by r10s** [comment] 2015-06-15 10:56
Same issue here with the calendar on 0.8.0, contacts work. However, syncing itself does not fail but always raises an error message.
After reinstallation and re-adding the baikal-server, everything is fine (i use the app for about one year and always updated through f-droid).

**Comment by DevCybran** [comment] 2015-07-17 17:24
This is probably the same issue as #523

**Comment by rfc2822** [comment] 2015-07-18 12:52
Yes, it's a duplicate of #523. Please follow up there.

Maybe someone can provide detailed steps to reproduce so that I can have a look at the issue?

**Closed by rfc2822** 2015-07-18 12:52 UTC
Labels: duplicate
