### ISSUE TITLE
False hour on calendar event after sync with davdroid 0.8.3

### ISSUE THREAD

**Issue by bvinsard** [bitfireAT/davdroid#606] opened 2015-08-16 17:27 UTC
A problem probably linked to timezone and summer time since the update from davdroid 0.8.2 to 0.8.3.
Description :
If an event is created on the remote device using davdroid at a given hour n, after sync with the server, the event switch to hour n+1 (on the server and on the remote device).
For example : an event is created from 19h to 20h. (Europe timezone)
After sync with the server, the event is from 19h to 20h (Europe timezone)
Configuration :
Server on GMT+2 timezone. Remote device on GMT+2 too.
Android 4.4.4
Temporary solution : 
Downgrade to davdroid 0.8.2

**Comment by devvv4ever** [comment] 2015-08-16 21:55
It's a duplicate of #186

Yes, we know of this. It is caused by another library we use and which already had a fix for it, but in it's current master the bug appeared again (and we used the master for the latest DAVdroid). You need to wait until we release 0.8.4 or (as you said downgrade temporarily). 

Keep in mind that only the display is wrong - the bug appears based on the day where we are right now. This probably won't show wrong again tomorrow or in some more days.

**Closed** 2015-08-25 19:21 UTC
Labels: duplicate
