### ISSUE TITLE
Anniversary can't be edited/created on android

### ISSUE THREAD

**Issue by Krakinou** [bitfireAT/davdroid#456] opened 2015-03-07 18:04 UTC
Hi, 
If I create a contact on my owncloud server, I can add anniversary data and it's correctly sync with android.
However, if I create a davdroid contact on the phone, anniversary does not appear on the field list, and I can't edit those from already existing contact. 
Davdroid 0.6.12  on galaxy s4, android 4.3
Server owncloud 7.02

**Comment by rfc2822** [comment] 2015-03-11 13:04
Duplicate of #426, please follow up there. Summary: This can't be done reliably without VCard/4 support because VCard/3 doesn't define anniversaries.

**Closed by rfc2822** 2015-03-11 13:04 UTC
Labels: duplicate

**Comment by Krakinou** [comment] 2015-03-14 08:12
Sorry, I had a transmission issue : the field I'm referring to is birthday, not anniversary. Here is an example of the vcf file from owncloud :
BEGIN:VCARD
VERSION:3.0
UID:c8442c3a-48a4-4a2e-a475-96c8677050bb
FN:Aaaaaaa
N:;Aaaaaaa;;;
PRODID:-//ownCloud//NONSGML Contacts 0.3.0.18//EN
REV:2015-03-06T18:18:36+00:00
BDAY;VALUE=DATE:1980-01-01
END:VCARD
As you can see, it uses BDAY. Moreover, the issue is slightly different : The birthday is sync, only it can't be edited/created on the android side:
![screenshot_2015-03-14-09-09-17](https://cloud.githubusercontent.com/assets/9308214/6650896/08fee02e-ca2a-11e4-9f2a-1a3f3856c670.png)
![screenshot_2015-03-14-09-09-28](https://cloud.githubusercontent.com/assets/9308214/6650902/2f98092c-ca2a-11e4-9816-98825b4f0748.png)

**Comment by devvv4ever** [comment] 2015-03-14 11:47
If it can't be edited on Android you need a different app for contacts. You can try "True Contacs" - this is an unbranded version of the Android contacts app.

DAVdroid is only the adapter for sync but has no influence which fields are editable on the device. Hope that helps!
