### ISSUE TITLE
After initial setup it is not possible to configure or see what's being synced

### ISSUE THREAD

**Issue by snackiz** [bitfireAT/davdroid#515] opened 2015-05-27 08:03 UTC
If I wish to see or change which of my calendars/contact lists/task lists are being synced, I can not find it without removing the current sync account and creating a new one.

**Comment by rfc2822** [comment] 2015-05-27 08:09
Duplicate of #219, please follow up there.

**Closed by rfc2822** 2015-05-27 08:09 UTC
