### ISSUE TITLE
group calendars not syncable?

### ISSUE THREAD

**Issue by posmanet** [bitfireAT/davdroid#538] opened 2015-06-06 19:57 UTC
Hello there!
I am using DAVdroid 0.8.0 on Android 4.4.4 with one CalDAV server. 

I have set it up with url, username and password. All private calendars from the server are selectable then, but none of the group calendars - and neither the public calendar from the server.

The private calendars' url are like these:
- https://somedomain.net/caldav/caldav.php/username/home/
- https://somedomain.net/caldav/caldav.php/username/private/

The group calendars' url are like this one:
- https://somedomain.net/caldav/caldav.php/groupname/calendar/

The public calendar's url is like this one:
- https://somedomain.net/caldav/caldav.php/+public/calendar/

Is this a bug? How can i subscribe to the group and public calendars? They don't show up in DAVdroid so i cannot select them...

**Comment by rfc2822** [comment] 2015-06-07 00:51
Thanks for your report, but it's a duplicate of #439.

**Closed by rfc2822** 2015-06-07 00:51 UTC
Labels: duplicate
