### ISSUE TITLE
Renaming calendar not replicate in andriod device account

### ISSUE THREAD

**Issue by wtayyeb** [bitfireAT/davdroid#450] opened 2015-02-24 08:07 UTC
Hi. I rename one of my calendars in owncloud and its new name appear in desktop client after few minuets. but the new name not changed in my android device either after force sync. finally I delete the account and add it again to make the change appear. This isn't the right way. I know you are busy but I think it it must requested, so it be planned to resolve someday.

Thanks.
Using davdroid 0.6.12 (latest)

**Comment by devvv4ever** [comment] 2015-02-24 09:35
Thank you for the enhancement request. We already made plans concerning this feature.
I'm closing this because it is duplicate of #154

**Closed by devvv4ever** 2015-02-24 09:35 UTC
